### ISSUE TITLE
[Bug] Unable to export mobilebert-uncased: `KeyError: 'pretraining'`

### ISSUE THREAD

**Issue by xenova** [huggingface/optimum#1027]
### System Info

```shell
- optimum version: source (latest commit as of this report)
- `transformers` version: 4.28.1
- Platform: Linux-5.10.147+-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.0+cu118 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.6.9 (cpu)
- Jax version: 0.4.8
- JaxLib version: 0.4.7
```

### Who can help?

@michaelbenayoun @fxmarty 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running this command:
```
optimum-cli export onnx -m google/mobilebert-uncased output
```

will produce this error:
```python
Framework not specified. Using pt to export to ONNX.
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/export/onnx.py", line 203, in run
    main_export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 169, in main_export
    model = TasksManager.get_model_from_task(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/tasks.py", line 1363, in get_model_from_task
    if TasksManager._TASKS_TO_LIBRARY[task.replace("-with-past", "")] == "transformers":
KeyError: 'pretraining'
```

This may be a similar issue to #991 

### Expected behavior

Model should export correctly.

**Comment by regisss** [comment]
Hi @xenova, it seems to be failing because there is no class `AutoModelForPreTraining` in Transformers. Would you like to have this model with its two heads (masked language modeling and next sentence prediction)?

**Comment by xenova** [comment]
I would imagine that the default task would be `fill-mask` and then `pretraining` would map to `feature-extraction` or something similar?

As outlined on the [model's repo](https://huggingface.co/google/mobilebert-uncased):

This is the intended usage:
```python
from transformers import pipeline

fill_mask = pipeline(
    "fill-mask",
    model="google/mobilebert-uncased",
    tokenizer="google/mobilebert-uncased"
)

print(
    fill_mask(f"HuggingFace is creating a {fill_mask.tokenizer.mask_token} that the community uses to solve NLP tasks.")
)

```

**Comment by regisss** [comment]
Actually the task is going to be inferred if you don't specify it in the command (see [here](https://github.com/huggingface/optimum/blob/5285732115000b78803154809cf7c05c180568f9/optimum/commands/export/onnx.py#L42)). And since the model class in the [`config.json`](https://huggingface.co/google/mobilebert-uncased/blob/main/config.json#L4) file is `MobileBertForPreTraining`, the inferred task is *pretraining*...
Not sure we have ever met this case before, I'll take a look to see how to improve task inference.
So in the meantime I would recommend that you add `--task fill-mask` or `--task feature-extraction` to your command.

**Comment by xenova** [comment]
Okay thanks!

**Comment by michaelbenayoun** [comment]
Yes, `MobileBertForPretraining` is actually `fill mask` + `next-sentence-prediction`. 
As @regisss said, I think what you want is either `fill-mask` or `feature-extraction`. Sorry for the inconvenience!

**Comment by xenova** [comment]
Was going through the list of supported models for transformers.js and tried exporting again:
```
optimum-cli export onnx -m google/mobilebert-uncased output --task feature-extraction
```

However, it results in output with max diff of 34 (>> 1e-5)

logs:
```
Framework not specified. Using pt to export to ONNX.
Using the export variant default. Available variants are:
	- default: The default ONNX variant.
Using framework PyTorch: 2.0.1+cu118
/usr/local/lib/python3.10/dist-packages/transformers/models/mobilebert/modeling_mobilebert.py:549: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.tensor(1000),
/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/jit_utils.py:306: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py:689: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_graph_shape_type_inference(
/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py:1186: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_graph_shape_type_inference(
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Post-processing the exported models...
Deduplicating shared (tied) weights...
The groups of weights [] will not be tied as either already tied or tying is not implemented.
Validating models in subprocesses...
Validating ONNX model output/model.onnx...
	-[✓] ONNX model output names match reference model (last_hidden_state)
	- Validating ONNX Model output "last_hidden_state":
		-[✓] (2, 16, 512) matches (2, 16, 512)
		-[x] values not close enough, max diff: 34.0 (atol: 0.0001)
The ONNX export succeeded with the warning: The maximum absolute difference between the output of the reference model and the ONNX exported model is not within the set tolerance 0.0001:
- last_hidden_state: max diff = 34.0.
 The exported model was saved at: output
```

considering this is an older architecture, it's not a massive issue by itself. However, if this is present in other models, then it's more important. cc @fxmarty
