### ISSUE TITLE
[Bug] Unable to export sentence-transformers/all-distilroberta-v1: `RuntimeError: number of output names provided (1) exceeded number of outputs (0)`

### ISSUE THREAD

**Issue by xenova** [huggingface/optimum#1028]
### System Info

```
- optimum version: source (latest commit as of this report)
- `transformers` version: 4.28.1
- Platform: Linux-5.10.147+-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.0+cu118 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.6.9 (cpu)
- Jax version: 0.4.8
- JaxLib version: 0.4.7
```

### Who can help?

@michaelbenayoun @fxmarty 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running this command:
```
optimum-cli export onnx -m sentence-transformers/all-distilroberta-v1 output
```

will produce this error:
```python
Framework not specified. Using pt to export to ONNX.
Some weights of RobertaForMaskedLM were not initialized from the model checkpoint at sentence-transformers/all-distilroberta-v1 and are newly initialized: ['lm_head.dense.bias', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Automatic task detection to feature-extraction.
Using framework PyTorch: 2.0.0+cu118
Overriding 1 configuration item(s)
	- use_cache -> False
============= Diagnostic Run torch.onnx.export version 2.0.0+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/export/onnx.py", line 203, in run
    main_export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 295, in main_export
    _, onnx_outputs = export_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 609, in export_models
    export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 697, in export
    export_output = export_pytorch(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 438, in export_pytorch
    onnx_export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1169, in _model_to_graph
    _set_input_and_output_names(graph, input_names, output_names)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1690, in _set_input_and_output_names
    set_names(list(graph.outputs()), output_names, "output")
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1667, in set_names
    raise RuntimeError(
RuntimeError: number of output names provided (1) exceeded number of outputs (0)
```

### Expected behavior

Model should export correctly.

**Comment by michaelbenayoun** [comment]
Should be fixed, please re-open this PR if it fails again.

**Comment by xenova** [comment]
> Should be fixed, please re-open this PR if it fails again.

Thanks! I'll test it and let you know if I run into any issues.

**Comment by maiiabocharova** [comment]
@michaelbenayoun 
I have the sample problem - here I created the [notebook](https://colab.research.google.com/drive/1BPaUAXJZ9P0XGjuP08Nht9qwdiwRjGAc?usp=sharing)  with export (I install optimum from source) which produces the error:
`RuntimeError: number of output names provided (1) exceeded number of outputs (0)`

**Comment by michaelbenayoun** [comment]
@maiiabocharova replied on the discuss thread, it should fix your issue!
