### ISSUE TITLE
Export decapoda-research/llama-7b-hf ONNX model failed

### ISSUE THREAD

**Issue by starlitsky2010** [huggingface/optimum#1055]
### System Info

```shell
optimum$ CUDA_VISIBLE_DEVICES=1 optimum-cli export onnx --model decapoda-research/llama-7b-hf --task causal-lm-with-past --fp16 --for-ort --device cuda llama-onnx
The option --for-ort was passed, but its behavior is now the default in the ONNX exporter and passing it is not required anymore.
Framework not specified. Using pt to export to ONNX.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:11<00:00,  2.88it/s]
use_past = False is different than use_present_in_outputs = True, the value of use_present_in_outputs value will be used for the outputs.
Using framework PyTorch: 2.0.1
Overriding 1 configuration item(s)
	- use_cache -> True
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:464: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_shape[-1] > 1:
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:49: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min, device=device), device=device)
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:112: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if seq_len > self.max_seq_len_cached:
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:217: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz, self.num_heads, q_len, kv_seq_len):
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:224: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.size() != (bsz, 1, q_len, kv_seq_len):
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:229: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  attn_weights = torch.max(attn_weights, torch.tensor(torch.finfo(attn_weights.dtype).min))
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:235: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz, self.num_heads, q_len, self.head_dim):
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Saving external data to one file...
/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:54: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/py10/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/optimum/commands/export/onnx.py", line 203, in run
    main_export(
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/optimum/exporters/onnx/__main__.py", line 295, in main_export
    _, onnx_outputs = export_models(
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/optimum/exporters/onnx/convert.py", line 609, in export_models
    export(
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/optimum/exporters/onnx/convert.py", line 714, in export
    config.fix_dynamic_axes(output, device=device, input_shapes=input_shapes, dtype=dtype)
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/optimum/exporters/onnx/base.py", line 255, in fix_dynamic_axes
    session = InferenceSession(model_path.as_posix(), providers=providers, sess_options=session_options)
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/user/anaconda3/envs/py10/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type (tensor(float)) of output arg (InsertedCast_/model/Cast_7_output_0) of node (/model/Cast_7) does not match expected type (tensor(float16)).

I've seen https://github.com/huggingface/optimum/pull/922
But can't reproduce model conversion successfully.
Could you give some help about it?

Thanks
```

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

$ CUDA_VISIBLE_DEVICES=1 optimum-cli export onnx --model decapoda-research/llama-7b-hf --task causal-lm-with-past --fp16 --for-ort --device cuda llama-onnx

### Expected behavior

To convert the llama7B ONNX model successfully.

**Comment by fxmarty** [comment]
Hi @starlitsky2010 , I can't reproduce on optimum main. Feel free to reopen if the issue persists.
