### ISSUE TITLE
Support for Document Question Answering

### ISSUE THREAD

**Issue by mgoin** [huggingface/optimum#1086]
### Feature request

It appears there is no support for the [`document-question-answering`](https://huggingface.co/tasks/document-question-answering) task. I am curious if this is expected to be particularly difficult or planned for future work?

### Motivation

It would be useful to accelerate and this is the most common finetuned task for LayoutLM and Donut, which are supported for `feature-extraction` already.

### Your contribution

I found this issue by attempting to export a finetuned DocVQA model using latest main:
```
optimum-cli export onnx -m naver-clova-ix/donut-base-finetuned-docvqa donut-base-finetuned-docvqa/
Framework not specified. Using pt to export to ONNX.
Traceback (most recent call last):
  File "/Users/mgoin/venv/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/Users/mgoin/venv/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/Users/mgoin/venv/lib/python3.10/site-packages/optimum/commands/export/onnx.py", line 203, in run
    main_export(
  File "/Users/mgoin/venv/lib/python3.10/site-packages/optimum/exporters/onnx/__main__.py", line 169, in main_export
    model = TasksManager.get_model_from_task(
  File "/Users/mgoin/venv/lib/python3.10/site-packages/optimum/exporters/tasks.py", line 1357, in get_model_from_task
    if TasksManager._TASKS_TO_LIBRARY[task.replace("-with-past", "")] == "transformers":
KeyError: 'document-question-answering'
```

**Comment by fxmarty** [comment]
Thank you, for sure we should add support for it! I don't expect it to be too much work, I can have a look next week.

**Comment by fxmarty** [comment]
Hi @mgoin, the export of vision-encoder-decoder models should work for the document-question-answering task following https://github.com/huggingface/optimum/pull/1110. LayoutLM should still be done, although I don't know if it used that much.

**Comment by mgoin** [comment]
Thank you for picking it up so quickly @fxmarty ! I'll give it a try
