### ISSUE TITLE
from_pretained typo and can not use config.json in optimum-cli quantize

### ISSUE THREAD

**Issue by YooSungHyun** [huggingface/optimum#1088]
### System Info

```shell
optimum==1.8.6
```

### Who can help?

@michaelbenayoun @jin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Use optimum-cli, and must use config

example
optimum-cli onnxruntime quantize --onnx_model ~~~ -o ~~~ -c ~~~/quantize_config.json

then error accur
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/onnxruntime/quantize.py", line 97, in run
    qconfig = ORTConfig.from_pretained(self.args.config).quantization
AttributeError: type object 'ORTConfig' has no attribute 'from_pretained'. Did you mean: 'from_pretrained'?

see this line. it is typo
https://github.com/huggingface/optimum/blob/main/optimum/commands/onnxruntime/quantize.py#L97

from_pretained -> from_pretrained

### Expected behavior

success quantize, using config json

**Comment by YooSungHyun** [comment]
and i think `ORTConfig.from_pretrained(self.args.config).quantization` is just dict. not QuantizationConfig. so, if `qconfig` input `quantize` function, it error occur (AttributeError: 'dict' object has no attribute 'is_static')

**Comment by YooSungHyun** [comment]
how about this way?

optimum.onnxruntime.configuration.py
``` python3
@staticmethod
def from_config(config: dict) -> QuantizationConfig:
    """
    Creates a [`~onnxruntime.QuantizationConfig`] from input config json file (default: ort_config.json)
    Args:
        config (`dict`):
            Input ONNX Runtime config file's (e.g. ort_config.json) `quantization` attribute
    """
    format, mode = default_quantization_parameters(is_static=config["is_static"])
    if config["activations_dtype"].lower() in ["u8", "quint8", "uint8"]:
        activations_dtype = QuantType.QUInt8
    else:
        activations_dtype = QuantType.QInt8
    if config["weights_dtype"].lower() in ["u8", "quint8", "uint8"]:
        weights_dtype = QuantType.QUInt8
    else:
        weights_dtype = QuantType.QInt8
    return QuantizationConfig(
        is_static=config["is_static"],
        format=format,
        mode=mode,
        activations_dtype=activations_dtype,
        activations_symmetric=config["activations_symmetric"],
        weights_dtype=weights_dtype,
        weights_symmetric=config["weights_symmetric"],
        per_channel=config["per_channel"],
        reduce_range=config["reduce_range"],
        nodes_to_quantize=config["nodes_to_quantize"] or [],
        nodes_to_exclude=config["nodes_to_exclude"] or [],
        operators_to_quantize=config["operators_to_quantize"] or ["MatMul", "Add"],
        qdq_add_pair_to_weight=config["qdq_add_pair_to_weight"],
        qdq_dedicated_pair=config["qdq_dedicated_pair"],
    )
```

optimum.commands.onnxruntime.quantize.py
``` python3
if self.args.arm64:
    qconfig = AutoQuantizationConfig.arm64(is_static=False, per_channel=self.args.per_channel)
elif self.args.avx2:
    qconfig = AutoQuantizationConfig.avx2(is_static=False, per_channel=self.args.per_channel)
elif self.args.avx512:
    qconfig = AutoQuantizationConfig.avx512(is_static=False, per_channel=self.args.per_channel)
elif self.args.avx512_vnni:
    qconfig = AutoQuantizationConfig.avx512_vnni(is_static=False, per_channel=self.args.per_channel)
elif self.args.tensorrt:
    qconfig = AutoQuantizationConfig.tensorrt(per_channel=self.args.per_channel)
else:
    qconfig = AutoQuantizationConfig.from_config(
        config=ORTConfig.from_pretrained(self.args.config).quantization
    )
```

I think it is work well

**Comment by YooSungHyun** [comment]
command line below....

``` bash
ORTConfig {
  "one_external_file": true,
  "opset": null,
  "optimization": {},
  "optimum_version": "1.8.6",
  "quantization": {
    "activations_dtype": "QInt8",
    "activations_symmetric": true,
    "format": "QDQ",
    "is_static": true,
    "mode": "QLinearOps",
    "nodes_to_exclude": [
      "/gpt_neox/layers.0/input_layernorm/ReduceMean_1_output_0"
    ],
    "nodes_to_quantize": [],
    "operators_to_quantize": [
      "MatMul",
      "Add"
    ],
    "per_channel": false,
    "qdq_add_pair_to_weight": true,
    "qdq_dedicated_pair": true,
    "reduce_range": false,
    "weights_dtype": "QInt8",
    "weights_symmetric": true
  },
  "transformers_version": "4.29.2",
  "use_external_data_format": true
}

Creating static quantizer: QDQ (mode: QLinearOps, schema: s8/s8, channel-wise: False)
.....
```

**Comment by YooSungHyun** [comment]
cc: @fxmarty

**Comment by YooSungHyun** [comment]
It will talk in https://github.com/huggingface/optimum/pull/1089 not here.
