### ISSUE TITLE
GPT-NeoX quantize error

### ISSUE THREAD

**Issue by YooSungHyun** [huggingface/optimum#1090]
### System Info

```shell
optimum==1.8.6
transformers==4.29.2
torch==2.0.1+cu117
```

### Who can help?

@michaelbenayoun 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

it is trained GPTNeoXForCausalLM (not code modify)
model config like this
``` json
{
  "_name_or_path": "",
  "architectures": [
    "GPTNeoXForCausalLM"
  ],
  "bos_token_id": 0,
  "classifier_dropout": 0.1,
  "eos_token_id": 0,
  "hidden_act": "gelu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 20480,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neox",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_steps": "global_step301000",
  "rotary_emb_base": 10000,
  "rotary_pct": 0.5,
  "tie_word_embeddings": false,
  "transformers_version": "4.29.2",
  "use_cache": false,
  "use_parallel_residual": true,
  "vocab_size": 30080
}
```

and export onnx model to `optimum-cli`
``` bash
optimum-cli export onnx --task text-generation --atol 1e-4 --model /workspace/model_path /workspace/onnx_default --framework pt
```

and then, do quantize to `optimum-cli`
``` bash
optimum-cli onnxruntime quantize --onnx_model /workspace/onnx_default -o /workspace/onnx_default/quantize --tensorrt
```

then error occured
``` bash
Creating static quantizer: QDQ (mode: QLinearOps, schema: s8/s8, channel-wise: False)
Quantizing model...
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/onnxruntime/quantize.py", line 102, in run
    q.quantize(save_dir=save_dir, quantization_config=qconfig)
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnxruntime/quantization.py", line 409, in quantize
    quantizer.quantize_model()
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/quantization/qdq_quantizer.py", line 217, in quantize_model
    self._quantize_normal_tensors()
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/quantization/qdq_quantizer.py", line 385, in _quantize_normal_tensors
    raise ValueError(
ValueError: Quantization parameters are not specified for param /gpt_neox/layers.0/input_layernorm/ReduceMean_1_output_0. In static mode quantization params for inputs and outputs of nodes to be quantized are required.
```

### Expected behavior

quantize success

**Comment by YooSungHyun** [comment]
my onnx dir like this
![image](https://github.com/huggingface/optimum/assets/34292279/370cbea4-1756-4c57-8d33-77017964c536)

**Comment by michaelbenayoun** [comment]
Hi @YooSungHyun,
Could you try with another quantization config, like `avx512` for instance? Just trying to see if it's related to the config itself.
cc @fxmarty

**Comment by YooSungHyun** [comment]
@michaelbenayoun thx for reply!
but i have to use tensorrt, if i use avx512 or someting, can i use TensorRT?

**Comment by YooSungHyun** [comment]
if i input "operators_to_quantize": ["MatMul", "Add", "ReduceMean"] then error occur like this

``` bash
Quantizing model...
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/onnxruntime/quantize.py", line 103, in run
    q.quantize(
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnxruntime/quantization.py", line 409, in quantize
    quantizer.quantize_model()
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/quantization/qdq_quantizer.py", line 217, in quantize_model
    self._quantize_normal_tensors()
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/quantization/qdq_quantizer.py", line 385, in _quantize_normal_tensors
    raise ValueError(
ValueError: Quantization parameters are not specified for param /gpt_neox/embed_in/Gather_output_0. In static mode quantization params for inputs and outputs of nodes to be quantized are required.
```

**Comment by michaelbenayoun** [comment]
Yes, just for the sake of pinpointing if it is from the config or from the model itself.

**Comment by YooSungHyun** [comment]
`--avx512` is done well.

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/onnxruntime/quantize.py", line 103, in run
    q.quantize(
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnxruntime/quantization.py", line 414, in quantize
    quantizer.model.save_model_to_file(quantized_model_path.as_posix(), use_external_data_format)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/quantization/onnx_model.py", line 346, in save_model_to_file
    onnx.save_model(self.model, output_path)
  File "/usr/local/lib/python3.10/dist-packages/onnx/__init__.py", line 231, in save_model
    s = _serialize(proto)
  File "/usr/local/lib/python3.10/dist-packages/onnx/__init__.py", line 75, in _serialize
    raise ValueError(
ValueError: The proto size is larger than the 2 GB limit. Please use save_as_external_data to save tensors separately from the model file.
```

it just onnx model size error, and maybe given `--use_external_data_format=True`, work fine i think

**Comment by YooSungHyun** [comment]
i think maybe static quantize problem...so, i tested ORTConfig like this (ORTConfig.from_pretrained using my fork source https://github.com/huggingface/optimum/pull/1089)

``` json
{
  "one_external_file": true,
  "opset": null,
  "optimization": {},
  "optimum_version": "1.8.6",
  "quantization": {
    "activations_dtype": "QUInt8",
    "activations_symmetric": true,
    "weights_dtype": "QInt8",
    "weights_symmetric": true,
    "reduce_range": false,
    "qdq_add_pair_to_weight": true,
    "qdq_dedicated_pair": true,
    "is_static": false,
    "per_channel": false,
    "nodes_to_quantize": [],
    "nodes_to_exclude": [],
    "operators_to_quantize": [
      "MatMul",
      "Add"
    ]
  },
  "transformers_version": "4.29.2",
  "use_external_data_format": true
}
```

it just different `"is_static": false,` and `"activations_dtype": "QUInt8"` between `--tensorrt` config (if want to use `is_static false`, must using `activations_dtype QUInt8`)

will test and sharing

**Comment by YooSungHyun** [comment]
it work well. it is problem with static quantize...
maybe, it is just raised output kind of things....so....very dangerous idea, just exclude them...?
i'm very wondering if `excluded them` make some accuracy problem (because, some node is 8bit and some node is fp32 or somting...)
``` bash
ORTConfig {
  "one_external_file": true,
  "opset": null,
  "optimization": {},
  "optimum_version": "1.8.6",
  "quantization": {
    "activations_dtype": "QUInt8",
    "activations_symmetric": true,
    "is_static": false,
    "nodes_to_exclude": [],
    "nodes_to_quantize": [],
    "operators_to_quantize": [
      "MatMul",
      "Add"
    ],
    "per_channel": false,
    "qdq_add_pair_to_weight": true,
    "qdq_dedicated_pair": true,
    "reduce_range": false,
    "weights_dtype": "QInt8",
    "weights_symmetric": true
  },
  "transformers_version": "4.29.2",
  "use_external_data_format": true
}

Creating dynamic quantizer: QOperator (mode: IntegerOps, schema: u8/s8, channel-wise: False)
Quantizing model...
Saving quantized model at: /workspace/LLM42_double_futher_single/onnx_default/quantize (external data format: True)
Configuration saved in /workspace/LLM42_double_futher_single/onnx_default/quantize/ort_config.json
```

**Comment by fxmarty** [comment]
Hi, TensorRT quantization requires calibration (ref: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#quantization) which is currently not supported through the command-line. I'll do a PR to improve the error message.

**Comment by YooSungHyun** [comment]
@fxmarty thx to your effort...!

what if i use huggingface python runtime code onnxruntime quantize..., it will be done well?

**Comment by fxmarty** [comment]
Yes sure! I suggest you to refer to the static quantization examples and to adapt them to work with tensorrt, which should be minimal work (change the quantization config): https://github.com/huggingface/optimum/tree/main/examples/onnxruntime/quantization. Unfortunately, there's not yet an example for text-generation (which is probably what you want with gpt neox).

**Comment by YooSungHyun** [comment]
@fxmarty what kind of calibration_tensors_range used? maybe i don't understand onnx quantize as well 😭
when i just convert fp32 onnx model to 8bit static onnx model, no need to care?

**Comment by fxmarty** [comment]
Hi @YooSungHyun , you can refer to ONNX Runtime implementation for calibration: https://github.com/microsoft/onnxruntime/blob/4f23577cb52334d84e7bbf7fb3404b4ceda2531b/onnxruntime/python/tools/quantization/calibrate.py#L271

But you normally should not have to care about these details - the ORT/Optimum API should abstract these details (e.g. following the examples I linked above).

**Comment by YooSungHyun** [comment]
@fxmarty i just using minmax for example...haha...
using `calibration_config = AutoCalibrationConfig.minmax(dataset)` and 
``` python3
ranges = quantizer.fit(
    dataset=dataset,
    calibration_config=calibration_config,
    operators_to_quantize=qconfig.operators_to_quantize,
    use_external_data_format = True,
    use_gpu=True
)
```

will be good i think so, but i using A100 80gb, if use_gpu=True, occur memory overflow error 😥
`Non-zero status code returned while running Mul node. Name:'/gpt_neox/layers.38/attention/Mul_5' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:368 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 44774656`

what i know using tensorrt, i have to quantize on cuda, haven't it?

and if it will be done, how can i validate? some validation function is it?

**Comment by YooSungHyun** [comment]
i using this code below,
``` python3
from optimum.onnxruntime import ORTQuantizer
from optimum.onnxruntime.configuration import AutoQuantizationConfig, AutoCalibrationConfig
from datasets import load_dataset
from transformers import AutoTokenizer
dataset = load_dataset("json", data_files="")["train"]
tokenizer = AutoTokenizer.from_pretrained(
    "/workspace/model_path", model_max_length=2048 , use_fast=False
)

import copy
USER = "User:"
SYSTEM = "System:"
UNUSED0 = "<|unused0|>"
UNUSED1 = "<|unused1|>"
UNUSED0_TOKEN_ID = 0
UNUSED1_TOKEN_ID = 1
IGNORE_INDEX = -100
def preprocess(raw):
    text = raw["data"].replace(USER, UNUSED0).replace(SYSTEM, UNUSED1) + tokenizer.eos_token

    tokenized_text = tokenizer(text, return_token_type_ids=False)
    labels = copy.deepcopy(tokenized_text.input_ids)
    for i in range(len(labels)):
        if labels[i] == UNUSED0_TOKEN_ID:
            j = i
            while True:
                if labels[j] == UNUSED1_TOKEN_ID:
                    labels[j] = IGNORE_INDEX
                    break
                else:
                    labels[j] = IGNORE_INDEX
                j += 1
                if j == len(labels) - 1:
                    # eos 토큰까지 왔다면
                    break
    raw["input_ids"] = tokenized_text["input_ids"]
    raw["labels"] = labels
    raw["attention_mask"] = tokenized_text["attention_mask"]
    return raw

dataset = dataset.map(preprocess, remove_columns=dataset.column_names,num_proc=4)
dataset = dataset.filter(lambda x: len(x["input_ids"]) <= 2048)

import torch
from optimum.onnxruntime import ORTModelForCausalLM
import os
os.environ["TORCHDYNAMO_DISABLE"] = "1"
model = ORTModelForCausalLM.from_pretrained(
    "/workspace/onnx_model_path",
    provider="CPUExecutionProvider",
    use_cache=False,
    use_io_binding=False,use_external_data_format =True
)
model = torch.compile(model)

import onnx
temp_model = onnx.load("/workspace/LLM42_double_futher_single/onnx_default/decoder_model.onnx")
model_inputs = {input.name for input in temp_model.graph.input}
ignored_columns = list(set(dataset.column_names) - model_inputs)
dataset = dataset.remove_columns(ignored_columns)

quantizer = ORTQuantizer.from_pretrained(model)
qconfig = AutoQuantizationConfig.tensorrt(per_channel=False)
calibration_config = AutoCalibrationConfig.minmax(dataset)
ranges = quantizer.fit(
    dataset=dataset,
    calibration_config=calibration_config,
    operators_to_quantize=qconfig.operators_to_quantize,
    use_external_data_format = True,
    use_gpu=False
)
```
