### ISSUE TITLE
Installation issue on Openvino NNcf

### ISSUE THREAD

**Issue by DebayanChakraborty** [huggingface/optimum#1095]
### System Info

```shell
LINUX WSL 2
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

OPTIMUM
Name: optimum
Version: 1.8.6
Summary: Optimum Library is an extension of the Hugging Face Transformers library, providing a framework to integrate third-party libraries from Hardware Partners and interface with their specific functionality.
Home-page: https://github.com/huggingface/optimum
Author: HuggingFace Inc. Special Ops Team
Author-email: hardware@huggingface.co
License: Apache
Location: /home/debayan/CT_with_LLM/opvino/lib/python3.11/site-packages
Requires: coloredlogs, datasets, huggingface-hub, numpy, packaging, sympy, torch, torchvision, transformers

PYTHON
3.11.3
```

### Who can help?

@echarlaix  , while trying to install openvino nncf, i am getting this issue and cannot figure out how to fix this problem. 
The hardware is intel and hence was working via this approach. I am trying to optimize blip model for image captioning

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-f8b_3uou/onnx_22d50665ccb74d03a417ba4977874f9c/setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python -m pip install optimum[openvino,nncf] is failing with the issue

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_g6qzuag/onnx_aebd33cd3ee44e7daf5f0a07afd43101/setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Expected behavior

installation should be successful

**Comment by fxmarty** [comment]
cc @echarlaix if you have any idea

**Comment by sudochia** [comment]
Got the same error as well, any ideas?
```
(venv) s@sudo-ubuntu:~/Desktop/test$ pip install 'optimum[openvino,nncf]'
Requirement already satisfied: optimum[nncf,openvino] in ./venv/lib/python3.11/site-packages (1.9.1)
Requirement already satisfied: coloredlogs in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (15.0.1)
Requirement already satisfied: sympy in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (1.12)
Requirement already satisfied: transformers[sentencepiece]>=4.26.0 in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (4.30.2)
Requirement already satisfied: torch>=1.9 in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (2.0.1)
Requirement already satisfied: packaging in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (23.1)
Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (1.25.1)
Requirement already satisfied: huggingface-hub>=0.8.0 in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (0.16.4)
Requirement already satisfied: datasets in ./venv/lib/python3.11/site-packages (from optimum[nncf,openvino]) (2.13.1)
Collecting optimum-intel[nncf]
  Using cached optimum-intel-1.9.3.tar.gz (81 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.8.0->optimum[nncf,openvino]) (3.12.2)
Requirement already satisfied: fsspec in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.8.0->optimum[nncf,openvino]) (2023.6.0)
Requirement already satisfied: requests in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.8.0->optimum[nncf,openvino]) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.8.0->optimum[nncf,openvino]) (4.65.0)
Requirement already satisfied: pyyaml>=5.1 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.8.0->optimum[nncf,openvino]) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.8.0->optimum[nncf,openvino]) (4.7.1)
Requirement already satisfied: networkx in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (3.1)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (11.7.91)
Requirement already satisfied: triton==2.0.0 in ./venv/lib/python3.11/site-packages (from torch>=1.9->optimum[nncf,openvino]) (2.0.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9->optimum[nncf,openvino]) (66.1.1)
Requirement already satisfied: wheel in ./venv/lib/python3.11/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9->optimum[nncf,openvino]) (0.40.0)
Requirement already satisfied: cmake in ./venv/lib/python3.11/site-packages (from triton==2.0.0->torch>=1.9->optimum[nncf,openvino]) (3.26.4)
Requirement already satisfied: lit in ./venv/lib/python3.11/site-packages (from triton==2.0.0->torch>=1.9->optimum[nncf,openvino]) (16.0.6)
Requirement already satisfied: regex!=2019.12.17 in ./venv/lib/python3.11/site-packages (from transformers[sentencepiece]>=4.26.0->optimum[nncf,openvino]) (2023.6.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in ./venv/lib/python3.11/site-packages (from transformers[sentencepiece]>=4.26.0->optimum[nncf,openvino]) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in ./venv/lib/python3.11/site-packages (from transformers[sentencepiece]>=4.26.0->optimum[nncf,openvino]) (0.3.1)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in ./venv/lib/python3.11/site-packages (from transformers[sentencepiece]>=4.26.0->optimum[nncf,openvino]) (0.1.99)
Requirement already satisfied: protobuf<=3.20.3 in ./venv/lib/python3.11/site-packages (from transformers[sentencepiece]>=4.26.0->optimum[nncf,openvino]) (3.20.3)
Requirement already satisfied: humanfriendly>=9.1 in ./venv/lib/python3.11/site-packages (from coloredlogs->optimum[nncf,openvino]) (10.0)
Requirement already satisfied: pyarrow>=8.0.0 in ./venv/lib/python3.11/site-packages (from datasets->optimum[nncf,openvino]) (12.0.1)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in ./venv/lib/python3.11/site-packages (from datasets->optimum[nncf,openvino]) (0.3.6)
Requirement already satisfied: pandas in ./venv/lib/python3.11/site-packages (from datasets->optimum[nncf,openvino]) (2.0.3)
Requirement already satisfied: xxhash in ./venv/lib/python3.11/site-packages (from datasets->optimum[nncf,openvino]) (3.2.0)
Requirement already satisfied: multiprocess in ./venv/lib/python3.11/site-packages (from datasets->optimum[nncf,openvino]) (0.70.14)
Requirement already satisfied: aiohttp in ./venv/lib/python3.11/site-packages (from datasets->optimum[nncf,openvino]) (3.8.4)
Collecting scipy
  Using cached scipy-1.11.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.2 MB)
Requirement already satisfied: accelerate in ./venv/lib/python3.11/site-packages (from optimum-intel[nncf]->optimum[nncf,openvino]) (0.21.0)
Collecting nncf>=2.5.0
  Using cached nncf-2.5.0-py3-none-any.whl (1.1 MB)
Collecting openvino-dev>=2023.0.0
  Using cached openvino_dev-2023.0.1-11005-py3-none-any.whl (5.9 MB)
Collecting openvino>=2023.0.0
  Using cached openvino-2023.0.1-11005-cp311-cp311-manylinux2014_x86_64.whl (36.8 MB)
Collecting onnx
  Using cached onnx-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.6 MB)
Collecting onnxruntime
  Using cached onnxruntime-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
Requirement already satisfied: mpmath>=0.19 in ./venv/lib/python3.11/site-packages (from sympy->optimum[nncf,openvino]) (1.3.0)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.11/site-packages (from aiohttp->datasets->optimum[nncf,openvino]) (1.3.1)
Collecting ninja<1.11,>=1.10.0.post2
  Using cached ninja-1.10.2.4-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (120 kB)
Collecting texttable>=1.6.3
  Using cached texttable-1.6.7-py2.py3-none-any.whl (10 kB)
Collecting scipy
  Using cached scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
Collecting networkx
  Using cached networkx-2.8.2-py3-none-any.whl (2.0 MB)
Collecting numpy
  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting pyparsing<3.0
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pymoo==0.5.0
  Using cached pymoo-0.5.0.tar.gz (706 kB)
  Preparing metadata (setup.py) ... done
Collecting jsonschema>=3.2.0
  Using cached jsonschema-4.18.3-py3-none-any.whl (80 kB)
Collecting pydot>=1.4.1
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting jstyleson>=0.0.2
  Using cached jstyleson-0.0.2.tar.gz (2.0 kB)
  Preparing metadata (setup.py) ... done
Collecting natsort>=7.1.0
  Using cached natsort-8.4.0-py3-none-any.whl (38 kB)
Collecting scikit-learn>=0.24.0
  Using cached scikit_learn-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
Collecting openvino-telemetry
  Using cached openvino_telemetry-2023.0.0-py3-none-any.whl (20 kB)
Collecting autograd>=1.3
  Using cached autograd-1.6.2-py3-none-any.whl (49 kB)
Collecting cma==2.7
  Using cached cma-2.7.0-py2.py3-none-any.whl (239 kB)
Collecting matplotlib>=3
  Using cached matplotlib-3.7.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Collecting addict>=2.4.0
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting defusedxml>=0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: opencv-python in ./venv/lib/python3.11/site-packages (from openvino-dev>=2023.0.0->optimum-intel[nncf]->optimum[nncf,openvino]) (4.8.0.74)
Requirement already satisfied: pillow>=8.1.2 in ./venv/lib/python3.11/site-packages (from openvino-dev>=2023.0.0->optimum-intel[nncf]->optimum[nncf,openvino]) (10.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas->datasets->optimum[nncf,openvino]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.11/site-packages (from pandas->datasets->optimum[nncf,openvino]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.11/site-packages (from pandas->datasets->optimum[nncf,openvino]) (2023.3)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests->huggingface-hub>=0.8.0->optimum[nncf,openvino]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.11/site-packages (from requests->huggingface-hub>=0.8.0->optimum[nncf,openvino]) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.11/site-packages (from requests->huggingface-hub>=0.8.0->optimum[nncf,openvino]) (2023.5.7)
Requirement already satisfied: psutil in ./venv/lib/python3.11/site-packages (from accelerate->optimum-intel[nncf]->optimum[nncf,openvino]) (5.9.5)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->torch>=1.9->optimum[nncf,openvino]) (2.1.3)
Collecting flatbuffers
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting onnxruntime
  Using cached onnxruntime-1.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
INFO: pip is looking at multiple versions of onnx to determine which version is compatible with other requirements. This could take a while.
Collecting onnx
  Using cached onnx-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
  Using cached onnx-1.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... done
Collecting protobuf<=3.20.3
  Using cached protobuf-3.20.1-py2.py3-none-any.whl (162 kB)
Collecting onnx
  Using cached onnx-1.11.0.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... done
  Using cached onnx-1.10.2.tar.gz (9.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six in ./venv/lib/python3.11/site-packages (from onnx->optimum-intel[nncf]->optimum[nncf,openvino]) (1.16.0)
  Using cached onnx-1.10.1.tar.gz (10.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached onnx-1.10.0.tar.gz (10.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1l38lqxr/onnx_17a0a29ac655453e9e8e283d7b062395/setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by regisss** [comment]
I cannot reproduce it. Your error seems related to this: https://github.com/onnx/onnx/issues/5254
What is the version of Python you are running? You can get it with `python --version`.
Is there anything else specific to your environment that make pip trying to install `onnx 1.10.0`? In my case, it installed the latest release of `onnx` and didn't have to look at former releases.

**Comment by echarlaix** [comment]
@DebayanChakraborty  @sudochia any news on this ? If you still observe this issue please let me know by opening an issue directly in [`optimum-intel`](https://github.com/huggingface/optimum-intel)

**Comment by sudochia** [comment]
it works now, the error does not exist anymore.
