### ISSUE TITLE
optimum for `onnx` pipelines do not work with tranformers `>=4.30`

### ISSUE THREAD

**Issue by davidberenstein1957** [huggingface/optimum#1119]
### System Info

```shell
optimum: 1.8
transformers: 4.30 (it does work for <4.30)
onnx: 1.14.0 (1.15.1 runtime)
max M1
```

### Who can help?

@philschmid @JingyaHuang, @echarlaix

```python
from optimum.pipelines import pipeline
classifier = pipeline(task="text-classification", accelerator="ort")
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the script from [here](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/pipelines)

```python
from optimum.pipelines import pipeline

classifier = pipeline(task="text-classification", accelerator="ort")
```

### Expected behavior

A prediction, but it results in the following stacktrace.

```bash
The argument `from_transformers` is deprecated, and will be removed in optimum 2.0.  Use `export` instead
Framework not specified. Using pt to export to ONNX.
Using framework PyTorch: 2.0.1
Overriding 1 configuration item(s)
        - use_cache -> False
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/Users/davidberenstein/Documents/programming/open-source/classy-classification/demo__tokens.py", line 6, in <module>
    nlp.add_pipe(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/spacy/language.py", line 786, in add_pipe
    pipe_component = self.create_pipe(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/spacy/language.py", line 679, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/confection/__init__.py", line 728, in resolve
    resolved, _ = cls._make(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/confection/__init__.py", line 777, in _make
    filled, _, resolved = cls._fill(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/confection/__init__.py", line 849, in _fill
    getter_result = getter(*args, **kwargs)
  File "/Users/davidberenstein/Documents/programming/open-source/classy-classification/classy_classification/__init__.py", line 65, in make_text_categorizer
    return ClassySpacyExternalZeroShot(
  File "/Users/davidberenstein/Documents/programming/open-source/classy-classification/classy_classification/classifiers/classy_spacy.py", line 142, in __init__
    ClassySkeleton.__init__(self, *args, **kwargs)
  File "/Users/davidberenstein/Documents/programming/open-source/classy-classification/classy_classification/classifiers/classy_skeleton.py", line 73, in __init__
    self.set_classification_model()
  File "/Users/davidberenstein/Documents/programming/open-source/classy-classification/classy_classification/classifiers/classy_spacy.py", line 166, in set_classification_model
    self.classifier = pipeline(task="text-classification", model=self.model, accelerator="ort")
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/optimum/pipelines/pipelines_base.py", line 376, in pipeline
    return transformers_pipeline(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 788, in pipeline
    framework, model = infer_framework_load_model(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/transformers/pipelines/base.py", line 280, in infer_framework_load_model
    framework = infer_framework(model.__class__)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/classy-classification-McR1jeWC-py3.10/lib/python3.10/site-packages/transformers/utils/generic.py", line 583, in infer_framework
    raise TypeError(f"Could not infer framework from class {model_class}.")
TypeError: Could not infer framework from class <class 'optimum.onnxruntime.modeling_ort.ORTModelForSequenceClassification'>.
```

**Comment by davidberenstein1957** [comment]
If possible, I would like to work on a fix for this.

**Comment by fxmarty** [comment]
Hi, running

```python
from optimum.pipelines import pipeline

classifier = pipeline(task="text-classification", accelerator="ort")
```

with

```
optimum                      1.8.8
transformers                 4.30.0
onnxruntime-gpu              1.15.0
onnx                         1.14.0
```

I can not reproduce the issue. Do you have more details on the setting you are encountering the issue with?

**Comment by fxmarty** [comment]
@davidberenstein1957 Thank you, there's currently an issue in the documentation building workflow - it will be fixed on the next release!
