### ISSUE TITLE
ValueError: whisper doesn't support task audio-classification for the onnx backend

### ISSUE THREAD

**Issue by xenova** [huggingface/optimum#1138]
### Feature request

It would be great if we could perform audio-classification with whisper. As an example, it could be used for language detection:
- https://huggingface.co/sanchit-gandhi/whisper-medium-fleurs-lang-id
- https://huggingface.co/sanchit-gandhi/whisper-base-ft-common-language-id
- https://huggingface.co/sanchit-gandhi/whisper-small-ft-common-language-id

(models by @sanchit-gandhi)

At the moment, running:
```bash
optimum-cli export onnx -m sanchit-gandhi/whisper-medium-fleurs-lang-id test
```
produces:
```bash
Framework not specified. Using pt to export to ONNX.
Downloading pytorch_model.bin: 100% 615M/615M [00:15<00:00, 39.0MB/s]
Automatic task detection to audio-classification.
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/export/onnx.py", line 219, in run
    main_export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 227, in main_export
    onnx_config_constructor = TasksManager.get_exporter_config_constructor(model=model, exporter="onnx", task=task)
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/tasks.py", line 1536, in get_exporter_config_constructor
    raise ValueError(
ValueError: whisper doesn't support task audio-classification for the onnx backend. Supported tasks are: feature-extraction, feature-extraction-with-past, automatic-speech-recognition, automatic-speech-recognition-with-past.
```

In the meantime, I can look into [audio-spectrogram-transformer models](https://huggingface.co/models?other=audio-spectrogram-transformer), as this export does seem to be supported by optimum.

### Motivation

This will mean audio-classification can be added as a supported task of Transformers.js.

### Your contribution

I will add audio-classification w/ whisper to Transformers.js.

**Comment by sanchit-gandhi** [comment]
Audio classification works pretty well with Whisper if you fine-tune it, but for language identification MMS LID is now definitely the new SoTA (https://huggingface.co/docs/transformers/main/en/model_doc/mms#language-identification-lid)

Wav2Vec should work with `audio-classification` in ONNX already right? There weren't any modelling changes required to get the existing transformers code to work with the new fairseq Wav2Vec2 MMS checkpoints

**Comment by xenova** [comment]
> but for language identification MMS LID is now definitely the new SoTA

Oh nice! I'll use that instead then 👍  I'll leave the feature request open for now, but if this is not worth implementing, it can be closed.
