### ISSUE TITLE
BetterTransformer GPT2 sets attention_mask to None and breaks forward pass

### ISSUE THREAD

**Issue by learning-chip** [huggingface/optimum#1179]
### System Info

```shell
- Optimum 1.9.1
- Transformers 4.30.2
- PyTorch 2.0.1+cu117
- DeepSpeed 0.9.2
```

### Who can help?

From the commit history, the `GPT2AttentionLayerBetterTransformer` in [decoder_models.py](https://github.com/huggingface/optimum/blob/v1.9.1/optimum/bettertransformer/models/decoder_models.py#L48) is done by @fxmarty I think. Also @younesbelkada and @baskrahmer  Thanks!

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

(update: same error can be reproduced without DeepSpeed, see later comment https://github.com/huggingface/optimum/issues/1179#issuecomment-1630038959)

Take the "minimum" reproducible script below -- looks a bit long, but most lines are just DeepSpeed boilerplate, modified from DeepSpeed [small_model_debugging/test_model.py](https://github.com/microsoft/DeepSpeed/blob/v0.9.5/tests/small_model_debugging/test_model.py) and Transformers [test_modeling_gpt2.py](https://github.com/huggingface/transformers/blob/v4.30.2/tests/models/gpt2/test_modeling_gpt2.py#L342) to train GPT2 with fake data using ZeRO:

```python
import argparse
import json
import os


import torch
from torch.utils.data.distributed import DistributedSampler

import transformers
from transformers import GPT2LMHeadModel, GPT2Config

# needs to import BetterTransformer before `zero.Init`, 
# see https://github.com/microsoft/DeepSpeed/issues/2812
from optimum.bettertransformer import BetterTransformer

import deepspeed
import deepspeed.comm as dist

def get_data_loader(batch_size, seq_length, vocab_size, total_samples, device, seed=42):
    torch.manual_seed(seed)
    train_data = torch.randint(vocab_size, size=(total_samples, seq_length), dtype=torch.long, device=device)
    train_dataset = torch.utils.data.TensorDataset(train_data)
    sampler = DistributedSampler(train_dataset)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, sampler=sampler)
    return train_loader

def create_config_from_dict(tmpdir, config_dict):
    config_path = os.path.join(tmpdir, 'temp_config.json')
    with open(config_path, 'w') as fd:
        json.dump(config_dict, fd)
    return config_path

def get_args(tmpdir, config_dict):
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int, default=int(os.environ['LOCAL_RANK']))
    parser.add_argument('--zero', type=int, default=3)
    parser.add_argument('--better_transformer', action='store_true', default=False)
    args = parser.parse_args()

    config_dict["zero_optimization"]["stage"] = args.zero
    config_path = create_config_from_dict(tmpdir, config_dict)

    args.deepspeed_config = config_path
    return args

config_dict = {
    "train_batch_size": 128,
    "train_micro_batch_size_per_gpu": 8, 
    "steps_per_print": 1,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00015,
        }
    },
    "zero_optimization": {
        "stage": 3,
    }
}

args = get_args('/tmp/', config_dict)


def main():
    
    print(torch.__version__, transformers.__version__, deepspeed.__version__)
    
    # https://github.com/microsoft/DeepSpeed/issues/3234#issuecomment-1574350337
    is_zero3 = (args.zero == 3)
    with deepspeed.zero.Init(enabled=is_zero3):
        gpt_config = GPT2Config(
            n_embd=32,
            n_head=8,
            n_layer=4,
            n_positions=1024
        )
        model = GPT2LMHeadModel(gpt_config)
        if args.better_transformer:
            model = BetterTransformer.transform(model)

    model, _, _, _ = deepspeed.initialize(args=args,
                                          model=model,
                                          model_parameters=model.parameters(),
                                          dist_init_required=True)

    data_loader = get_data_loader(
        batch_size=model.train_micro_batch_size_per_gpu(),
        seq_length=gpt_config.n_positions,
        vocab_size=gpt_config.vocab_size,
        total_samples=model.train_batch_size(),  # one epoch
        device=model.device
    )

    for step, batch in enumerate(data_loader):
        outputs = model(input_ids=batch[0], labels=batch[0])
        # bug occurs in forward pass before entering backward pass
        loss = outputs.loss
        model.backward(loss)
        model.step()

        if dist.get_rank() == 0:
            print(f"step {step}, loss: {loss.item()}")

if __name__ == '__main__':
    main()
```

The script works without BetterTransformer:
```
torchrun --nproc_per_node 2 --nnodes 1 better_transformer_zero_init.py  # ZeRO3
torchrun --nproc_per_node 2 --nnodes 1 better_transformer_zero_init.py --zero 2
```

But fails with BetterTransformer enabled :
```
torchrun --nproc_per_node 2 --nnodes 1 better_transformer_zero_init.py --better_transformer
torchrun --nproc_per_node 2 --nnodes 1 better_transformer_zero_init.py --zero 2 --better_transformer
```

Already considers https://github.com/microsoft/DeepSpeed/issues/2812, otherwise will hit another error.

### Expected behavior

- Expect to train GPT2 BetterTransformer using DeepSpeed ZeRO without error.
- Expect to have unit tests to ensure compatibility between BetterTransformer and DeepSpeed ZeRO training.

Current error log:

```
TypeError: unsupported operand type(s) for +: 'Tensor' and 'NoneType'
Traceback (most recent call last):
  File "better_transformer_zero_init.py", line 102, in <module>
    main()
  File "better_transformer_zero_init.py", line 95, in main
    outputs = model(input_ids=batch[0], labels=batch[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ma-user/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1724, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1080, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 903, in forward
    outputs = block(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 391, in forward
    attn_outputs = self.attn(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/.local/lib/python3.8/site-packages/optimum/bettertransformer/models/decoder_models.py", line 74, in forward
    return super().forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 332, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/ma-user/.local/lib/python3.8/site-packages/optimum/bettertransformer/models/attention.py", line 77, in gpt2_wrapped_scaled_dot_product
    attention_mask = causal_mask + attention_mask
```

**Comment by learning-chip** [comment]
Is there a way to directly define a model class like `GPT2withBetterTransformer`, without a separate `BetterTransformer.transform` call? This seems more compatible with DeepSpeed wrapper.

**Comment by learning-chip** [comment]
**update**: The same error can be reproduced without using DeepSpeed. More likely because BetterTransformer changes input signature?

The single-device training script:

```python
import argparse
import os
import json

import numpy as np
import torch

from transformers import GPT2LMHeadModel, GPT2Config

parser = argparse.ArgumentParser()
parser.add_argument('--device', type=str, default='cpu')
parser.add_argument('--better_transformer', action='store_true', default=False)

args = parser.parse_args()

def get_data_loader(batch_size, seq_length, vocab_size, total_samples, device, seed=42):
    torch.manual_seed(seed)
    train_data = torch.randint(vocab_size, size=(total_samples, seq_length), device=device)
    train_dataset = torch.utils.data.TensorDataset(train_data)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size)
    return train_loader

def main():
    device = args.device

    gpt_config = GPT2Config(
        n_embd=32,
        n_head=8,
        n_layer=4,
        n_positions=1024
    )
    model = GPT2LMHeadModel(gpt_config)

    if args.better_transformer:
        from optimum.bettertransformer import BetterTransformer
        model = BetterTransformer.transform(model)

    model.to(device)

    data_loader = get_data_loader(
        batch_size=8,
        seq_length=gpt_config.n_positions,
        vocab_size=gpt_config.vocab_size,
        total_samples=32,
        device=device
    )

    optimizer = torch.optim.AdamW(model.parameters())

    for epoch in range(3):
        print(f"==== epoch: {epoch} ====")
        for step, batch in enumerate(data_loader):
            optimizer.zero_grad()
            outputs = model(input_ids=batch[0], labels=batch[0])
            loss = outputs.loss
            loss.backward()
            optimizer.step()
            print(f"{step}: {loss.cpu().detach().numpy()}")

if __name__ == '__main__':
    main()
```

Works with original model:
```bash
python ./better_transformer_gpt.py --device cuda
```

Failed with `BetterTransformer`:
```bash
python ./better_transformer_gpt.py --device cuda --better_transformer
python ./better_transformer_gpt.py --better_transformer  # same error on CPU
```

Error log:
```
Traceback (most recent call last):
  File "./gpt_random_data.py", line 67, in <module>
    main()
  File "./gpt_random_data.py", line 60, in main
    outputs = model(input_ids=batch[0], labels=batch[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1080, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 903, in forward
    outputs = block(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 391, in forward
    attn_outputs = self.attn(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/.local/lib/python3.8/site-packages/optimum/bettertransformer/models/decoder_models.py", line 74, in forward
    return super().forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 332, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/ma-user/.local/lib/python3.8/site-packages/optimum/bettertransformer/models/attention.py", line 77, in gpt2_wrapped_scaled_dot_product
    attention_mask = causal_mask + attention_mask
TypeError: unsupported operand type(s) for +: 'Tensor' and 'NoneType'
```

**Comment by learning-chip** [comment]
I do get a warning `WARNING:root:For training, the BetterTransformer implementation for gpt2  architecture currently does not support padding as fused kernels do not support custom attention masks. Beware that passing padded batched training data may result in unexpected outputs.`

But I don't think custom attention masks are used in the above example?

**Comment by learning-chip** [comment]
A even smaller error reproducer with only forward pass:

```python
import argparse

import numpy as np
import torch

from transformers import GPT2LMHeadModel, GPT2Config

parser = argparse.ArgumentParser()
parser.add_argument('--device', type=str, default='cpu')
parser.add_argument('--better_transformer', action='store_true', default=False)

args = parser.parse_args()


def main():
    device = args.device

    gpt_config = GPT2Config(
        n_embd=32,
        n_head=8,
        n_layer=4,
        n_positions=1024
    )
    model = GPT2LMHeadModel(gpt_config)

    if args.better_transformer:
        from optimum.bettertransformer import BetterTransformer
        model = BetterTransformer.transform(model)

    model.to(device)

    batch_size = 8
    batch = torch.randint(
        gpt_config.vocab_size, 
        size=(batch_size, gpt_config.n_positions), 
        device=device
    )
    print(batch.shape)
    outputs = model(input_ids=batch, labels=batch)
    print(outputs.loss, outputs.logits.shape)


if __name__ == '__main__':
    main()
```

```bash
python ./better_transformer_gpt_forward.py  # pass
python ./better_transformer_gpt_forward.py --better_transformer  # fail
```

**Comment by fxmarty** [comment]
hi @learning-chip, thanks, fixed in https://github.com/huggingface/optimum/pull/1180. Note that the issue should happen only if the model is in eval mode with `batch_size > 1` and no attention mask is passed, which is arguably not very likely? Given that in batched inference normally padding is used (unless more fancy nestedtensor or indexing is used).
