### ISSUE TITLE
custom_onnx_configs 

### ISSUE THREAD

**Issue by mgoin** [huggingface/optimum#1190]
### System Info

```shell
python 3.10.6
optimum 1.9.2.dev0 (c4750f6014d8ac39bca780e1e4381b15eaab9197)
torch 2.0.1
onnx 1.14.0
```
```


### Who can help?

@michaelbenayoun 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from optimum.exporters.onnx import main_export
from optimum.exporters.onnx.model_configs import ViTOnnxConfig

model_id = "snap-research/efficientformer-l1-300"
main_export(
    model_id,
    output="ef_test",
    task="image-classification",
    custom_onnx_configs={"model": ViTOnnxConfig},
)
```

Stacktrace:
```
Traceback (most recent call last):
  File "~/ef.py", line 8, in <module>
    main_export(
  File "~/optimum/optimum/exporters/onnx/__main__.py", line 442, in main_export
    _, onnx_outputs = export_models(
  File "~/optimum/optimum/exporters/onnx/convert.py", line 758, in export_models
    export(
  File "~/optimum/optimum/exporters/onnx/convert.py", line 861, in export
    export_output = export_pytorch(
  File "~/optimum/optimum/exporters/onnx/convert.py", line 541, in export_pytorch
    logger.info(f"Overriding {len(config.values_override)} configuration item(s)")
TypeError: object of type 'property' has no len()
```

Then if I remove that section (since it is just because there is some back interaction with a None property not registering as actually None), the config doesn't seem to be setup right for usage here.
```
  File "~/optimum/optimum/exporters/onnx/convert.py", line 550, in export_pytorch
    dummy_inputs = config.generate_dummy_inputs(framework="pt", **input_shapes)
TypeError: OnnxConfig.generate_dummy_inputs() missing 1 required positional argument: 'self'
```

### Expected behavior

Expected ONNX export to work as if "efficientformer" was added to the set of supported models. I can do this if there is interest, but I am interested in the flexibility of using `custom_onnx_configs` for quick prototyping.

I noticed [all the documentation](https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models) for this pathway seem to be for more complex model types i.e. encoder-decoder or decoder-only. Perhaps expanding this for simple custom models would be simple and I think very useful! Thank you.

**Comment by regisss** [comment]
Hi @mgoin! In the `custom_onnx_configs` arg, you actually need to pass an instantiated ONNX configuration and not the class itself.

Here is how to do it:
```py
from optimum.exporters.onnx import main_export
from optimum.exporters.onnx.model_configs import ViTOnnxConfig
from transformers import AutoConfig

model_id = "snap-research/efficientformer-l1-300"
task = "image-classification"
main_export(
    model_id,
    output="ef_test",
    task=task,
    custom_onnx_configs={
        "model": ViTOnnxConfig(
            config=AutoConfig.from_pretrained(model_id),
            task=task,
        ),
    },
)
```
Let me know if that also works on your side :slightly_smiling_face: 
And don't hesitate to open a PR to add official support for EfficientFormer, that will enable users to quickly export such models with the CLI :rocket:

**Comment by mgoin** [comment]
Hey @regisss that worked simply enough, appreciate the quick and easy response. Thank you!
