### ISSUE TITLE
Exporting SwitchTransformer model throws RuntimeError

### ISSUE THREAD

**Issue by shaahji** [huggingface/optimum#1281]
### System Info

```shell
optimum==1.11.0
onnx==1.14.0
onnxruntime==1.15.1
torch==2.0.1
platform=Windows
Python=3.10
```

### Who can help?

@michaelbenayoun @JingyaHuang, @echarlaix

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```
from optimum.exporters.onnx import main_export as export_optimum_model
from optimum.exporters.onnx.model_configs import T5OnnxConfig
from transformers import SwitchTransformersConfig

with open('config.json', 'r') as strm:
  import json
  config_data = json.load(strm)

pretrained_config = SwitchTransformersConfig(**config_data)
custom_onnx_config = T5OnnxConfig(pretrained_config)
onnx_configs = {
  "encoder_model": custom_onnx_config.with_behavior("encoder", use_past=False),
  "decoder_model": custom_onnx_config.with_behavior("decoder", use_past=False),
  "decoder_with_past_model": custom_onnx_config.with_behavior("decoder", use_past=True),
}

export_optimum_model(
  "google/switch-base-8",
  output="models/",
  opset=16,
  framework="pt",
  no_post_process=True,
  task="text2text-generation-with-past",
  custom_onnx_configs=onnx_configs,
)
```

Generated RuntimeError -
```
Traceback (most recent call last):
  File "<Local_Directory>\switch\py_inference.py", line 70, in <module>
    export_optimum_model(
  File "<Python_Directory>\Python310\site-packages\optimum\exporters\onnx\__main__.py", line 446, in main_export
    _, onnx_outputs = export_models(
  File "<Python_Directory>\Python310\site-packages\optimum\exporters\onnx\convert.py", line 760, in export_models
    export(
  File "<Python_Directory>\Python310\site-packages\optimum\exporters\onnx\convert.py", line 863, in export
    export_output = export_pytorch(
  File "<Python_Directory>\Python310\site-packages\optimum\exporters\onnx\convert.py", line 580, in export_pytorch
    onnx_export(
  File "<Python_Directory>\Python310\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "<Python_Directory>\Python310\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "<Python_Directory>\Python310\site-packages\torch\onnx\utils.py", line 1169, in _model_to_graph
    _set_input_and_output_names(graph, input_names, output_names)
  File "<Python_Directory>\Python310\site-packages\torch\onnx\utils.py", line 1690, in _set_input_and_output_names
    set_names(list(graph.outputs()), output_names, "output")
  File "<Python_Directory>\Python310\site-packages\torch\onnx\utils.py", line 1667, in set_names
    raise RuntimeError(
RuntimeError: number of output names provided (49) exceeded number of outputs (48)
```

### Expected behavior

Exporter generates onnx model

**Comment by fxmarty** [comment]
Hi @shaahji the export of switch transformer to ONNX is not officially supported.

I am not sure to understand what your use case is though? MOE models are usually deployed over several devices, which ONNX Runtime (or e.g. TensorRT) is not fit for.

**Comment by shaahji** [comment]
> the export of switch transformer to ONNX is not officially supported.

Is adding switch transformer on the roadmap?

> I am not sure to understand what your use case is though?

To begin, I am merely trying to export the model to onnx. I am planning on using onnxruntime-gpu with support for collective operations (i.e. MPI/NCCL support).

**Comment by fxmarty** [comment]
@shaahji As a far as I know there is no PP or TP support in ORT CUDA EP. How would having a standalone ONNX help you?

**Comment by shaahji** [comment]
@fxmarty I am experimenting with distributing experts in an MoE model across multiple GPUs and use MPI for inferencing.

**Comment by fxmarty** [comment]
Thank you @shaahji, I'll try to add the support soon. Feel free to open a PR as well.
