### ISSUE TITLE
M2M100ForConditionalGeneration with BetterTransformer cannot return attentions

### ISSUE THREAD

**Issue by comchobo** [huggingface/optimum#1302]
### System Info

```shell
torch= 2.0.1 + cu118
transformers= from source (4.32.dev0)
optimum= from source (1.11.3dev0)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

The datasets I have just include 'korean' and 'English' rows.

Following code makes error
```python
model_path = 'facebook/nllb-200-distilled-600M'
model = M2M100ForConditionalGeneration.from_pretrained(model_path, device_map="auto").eval()
model.to(device)
def tokenize(row):
    return tokenizer(row['ko'], truncation=True, max_length=85, return_offsets_mapping=True,)
tokenized_train_dataset = train_dataset.map(tokenize, batched=True)

translated_tokens = model.generate(
    **inputs, forced_bos_token_id=tokenizer.lang_code_to_id["eng_Latn"], max_length=180,
    return_dict_in_generate=True, output_scores=True, output_attentions=True)
```

```
The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.
Map: 100%|██████████| 1539/1539 [00:00<00:00, 19574.94 examples/s]
Map: 100%|██████████| 1539/1539 [00:00<00:00, 19943.44 examples/s]
  0%|          | 0/154 [00:00<?, ?it/s]You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
C:\Users\(user)\PycharmProjects\project\venv\lib\site-packages\optimum\bettertransformer\models\encoder_models.py:675: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ..\aten\src\ATen\NestedTensorImpl.cpp:179.)
  hidden_states = torch._nested_tensor_from_mask(hidden_states, ~attention_mask)
==Prune dataset==
  0%|          | 0/154 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\(user)\PycharmProjects\project\main_prune_dataset.py", line 65, in <module>
    translated_tokens = model.generate(
  File "C:\Users\(user)\PycharmProjects\project\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\(user)\PycharmProjects\project\venv\lib\site-packages\transformers\generation\utils.py", line 1486, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "C:\Users\(user)\PycharmProjects\project\venv\lib\site-packages\transformers\generation\utils.py", line 655, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "C:\Users\(user)\PycharmProjects\project\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\(user)\PycharmProjects\project\venv\lib\site-packages\transformers\models\m2m_100\modeling_m2m_100.py", line 850, in forward
    all_attentions = all_attentions + (layer_outputs[1],)
IndexError: tuple index out of range
python-BaseException
```

And, without `output_attentions=True`, it works.
```python
            translated_tokens = model.generate(
                **inputs, forced_bos_token_id=tokenizer.lang_code_to_id["eng_Latn"], max_length=180,
                return_dict_in_generate=True, output_scores=True)
```

I guess 'nested tensor' datatype is making some errors maybe? Would you guys help?

### Expected behavior

`translated_tokens` would return `GreedySearchEncoderDecoderOutput`, which has `attentions` tuple value.

**Comment by fxmarty** [comment]
Hi @comchobo, `output_attention=True` is not supported with BetterTransformer / pytorch nested tensor optimization. Although we have safety checks for it in the decoder, it is missing from the encoder hence the not-so-meaningful error. I'll fix, thank you.
