### ISSUE TITLE
Can't use bettertransformer to train vit?

### ISSUE THREAD

**Issue by lijiaoyang** [huggingface/optimum#1379]
### System Info

```shell
Traceback (most recent call last):
  File "test_bettertransformer_vit.py", line 95, in <module>
    main()
  File "test_bettertransformer_vit.py", line 92, in main
    test_train_time()
  File "test_bettertransformer_vit.py", line 86, in test_train_time
    out_vit = model(pixel_values).last_hidden_state
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 587, in forward
    encoder_outputs = self.encoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 413, in forward
    layer_outputs = layer_module(hidden_states, layer_head_mask, output_attentions)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/optimum/bettertransformer/models/encoder_models.py", line 1186, in forward
    raise NotImplementedError(
NotImplementedError: Training and Autocast are not implemented for BetterTransformer + ViT. Please open an issue.
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

def test_train_time():
    model = ViTModel.from_pretrained(model_pth).to('cuda')
    processor = ViTImageProcessor.from_pretrained(model_pth)
    pixel_values=clip_process(processor, pic_pth).cuda()
    if args.flash:
        model = model.to_bettertransformer()
    model.train()

    begin_time = time.time()
    for i in range(args.nums):
        out_vit = model(pixel_values).last_hidden_state

    print('use flash: {}, train vit time {:.2f}'.format(args.flash, time.time() - begin_time)) 

### Expected behavior

none

**Comment by fxmarty** [comment]
@lijiaoyang Thank you for the report. Indeed the implementation is not done for ViT, that is available only for training. I'll add it to my todo, hopefully should not be complicated!
