### ISSUE TITLE
Using `onnxruntime-gpu`, specifying the execution provider is necessary

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#138]
This issue should be fixed with https://github.com/huggingface/optimum/pull/137 .

## Reproduce

One may want to run inference on a GPU.

1. `pip uninstall onnx onnxruntime optimum`
2. `pip install onnx onnxruntime-gpu`
3. `pip install optimum[dev]`
4. run e.g. https://github.com/huggingface/optimum/blob/main/examples/onnxruntime/quantization/text-classification/run_glue.py with `python run_glue.py --model_name_or_path howey/bert-base-uncased-sst2 --task_name sst2 --quantization_approach static --do_eval --output_dir /tmp/quantized_distilbert_sst2 --max_eval_samples 50 --num_calibration_samples 50`
## Error raised

```
Traceback (most recent call last):
  File "/home/fxmarty/hf_internship/optimum/examples/onnxruntime/quantization/text-classification/run_glue.py", line 519, in <module>
    main()
  File "/home/fxmarty/hf_internship/optimum/examples/onnxruntime/quantization/text-classification/run_glue.py", line 481, in main
    outputs = ort_model.evaluation_loop(eval_dataset)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/optimum/onnxruntime/model.py", line 84, in evaluation_loop
    session = InferenceSession(self.model_path.as_posix(), options)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 363, in _create_inference_session
    raise ValueError("This ORT build has {} enabled. ".format(available_providers) +
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
```

i.e. https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_inference_collection.py#L361

## Why this issue

We install `onnxruntime-gpu` and not `onnxruntime`, hence have access to additional providers ('TensorrtExecutionProvider', 'CUDAExecutionProvider') which triggers the error raise. Installing `onnxruntime` on top of `onnxruntime-gpu` makes the additional providers unvisible and only 'CPUExecutionProvider' becomes available.

**Comment by echarlaix** [comment]
Issue fixed by [PR#137](https://github.com/huggingface/optimum/pull/137)
