### ISSUE TITLE
Runtime Error when Quantizing Llama2

### ISSUE THREAD

**Issue by kokybo** [huggingface/optimum#1392]
### System Info

```shell
accelerate==0.22.0       
auto-gptq==0.4.2+cu118
optimum==1.13.1
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchvision==0.15.2+cu118
transformers==4.33.1

Running in a WSL Docker container using CUDA 11.8. With a Nvidia GeForce 1050 Graphics Card
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Running the following script that is based on the Huggingface documentation [here] (https://huggingface.co/docs/transformers/main/en/main_classes/quantization#quantize-transformers-models) produces the error below which appears to arise from the optimum codebase
```python
from accelerate import init_empty_weights, infer_auto_device_map
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM, GPTQConfig
import logging
import torch

logging.basicConfig(
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s", level=logging.INFO, datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger()

max_memory = {"cpu": "15GiB"}

model_name = "models/llama2-7b-chat"
output_dir = "models/llama2-7b-chat-4bit-hf"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
examples = [
    "auto-gptq is an easy-to-use model quantization library with user-friendly apis, based on GPTQ algorithm."
]

logger.info("Loaded tokenizer and tokenized examples")

config = AutoConfig.from_pretrained(model_name)
with init_empty_weights():
    temp = AutoModelForCausalLM.from_config(config)

device_map = infer_auto_device_map(temp, max_memory=max_memory, dtype="float16")

# Force model to load into CPU Ram
for layer in device_map:
    # if device_map[layer] == "disk":
    #     device_map[layer] = "cpu"
    device_map[layer] = "cpu"

logger.info("Generated Device Map for Quantization")

quantize_config = GPTQConfig(
    bits=4,  # quantize model to 4-bit
    dataset=examples,
    tokenizer=tokenizer,
    use_cuda_fp16=True,
    disable_exllama=False
)

logger.info("Loading Model into Memory and Quantizing")
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map=device_map,
    max_memory=max_memory,
    # offload_folder="/offload",
    quantization_config=quantize_config,
    torch_dtype=torch.float16
)

logger.info("Saving Quantized Model")
model.save_pretrained(output_dir)
```
```
Traceback (most recent call last):
  File "/usr/src/app/examples/quantize_llama.py", line 47, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3241, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/optimum/gptq/quantizer.py", line 363, in quantize_model
    model(**data)
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 820, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
```

### Expected behavior

The expected behavior is the model should load and quantize normally. I have confirmed that I am able to quantize the model using the AutoGPTQ package directly

**Comment by IlyasMoutawwakil** [comment]
Hi @kokybo, GPTQ kernels are `cuda` kernels and can't run on CPU. You can use offloading to minimize GPU memory usage, but full CPU is not possible.

**Comment by kokybo** [comment]
@IlyasMoutawwakil That makes sense. however, the problem still occurs if I change the configuration at the top for accelerate to 

```python
for layer in device_map:
    if device_map[layer] == "disk":
        device_map[layer] = "cpu"
    # device_map[layer] = "cpu"
```

which based on my understanding should allow the model to use the GPU as well as offload to the CPU?

**Comment by SunMarc** [comment]
Hi @kokybo, you don't need to pass a `device_map` in that case. it will move the layers to the GPU when needed during the quantization.
