### ISSUE TITLE
Convert llama 2 hf to tflite issue

### ISSUE THREAD

**Issue by yige0617** [huggingface/optimum#1415]
### System Info

```shell
optimum                       1.13.2
python                        3.11.4
platform                      cuda 11.8
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Failed to convert llama-7b-hf into tflite model
optimum-cli export tflite --model "path\to\Llama-2-7b-chat-hf"  --task causal-lm-with-past --sequence_length 128 tflite_llama
Got following log
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myname\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\exporters\tflite\__main__.py", line 146, in <module>
    main()
  File "C:\Users\myname\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\exporters\tflite\__main__.py", line 61, in main
    model = TasksManager.get_model_from_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\exporters\tasks.py", line 1481, in get_model_from_task
    if TasksManager._TASKS_TO_LIBRARY[task.replace("-with-past", "")] == "transformers":
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'causal-lm'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myname\AppData\Local\anaconda3\Scripts\optimum-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\myname\AppData\Local\anaconda3\Lib\site-packages\optimum\commands\optimum_cli.py", line 163, in main
    service.run()
  File "C:\Users\myname\AppData\Local\anaconda3\Lib\site-packages\optimum\commands\export\tflite.py", line 243, in run
    subprocess.run(full_command, shell=True, check=True)
  File "C:\Users\myname\AppData\Local\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.tflite --model C:\Users\myname\Llama-2-7b-chat-hf --task causal-lm-with-past --sequence_length 128 tflite_llama' returned non-zero exit status 1




### Expected behavior

Should export tflite model without error

**Comment by fxmarty** [comment]
Thank you for the report @yige0617, apology for the delay. Using optimum 1.13.2, and running `optimum-cli export tflite --model fxmarty/tiny-llama-fast-tokenizer llama_tflite --task causal-lm`, the error message I am getting is:

```
ValueError: Unrecognized configuration class <class 'transformers.models.llama.configuration_llama.LlamaConfig'> for this kind of AutoModel: TFAutoModelForCausalLM.
Model type should be one of BertConfig, CamembertConfig, CTRLConfig, GPT2Config, GPT2Config, GPTJConfig, OpenAIGPTConfig, OPTConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoFormerConfig, TransfoXLConfig, XGLMConfig, XLMConfig, XLMRobertaConfig, XLNetConfig.
```

Unfortunately, this indicates that Llama has no implementation in TensorFlow in Transformers currently. This can be confirmed [here](https://huggingface.co/docs/transformers/v4.34.0/en/model_doc/llama#overview). Feel free to open an issue (or a PR!) in Transformers if you would like the implementation to be added.
