### ISSUE TITLE
open_clip model onnx export not supported 

### ISSUE THREAD

**Issue by alachyan-ml** [huggingface/optimum#1450]
### System Info

```shell
Python 3.9.16
optimum 1.13.2
Ubuntu 20.04.6 LTS
```

### Who can help?

@michaelbenayoun 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

 ```% optimum-cli export onnx -m laion/CLIP-ViT-B-32-256x256-DataComp-s34B-b86K --framework pt ./clip --task zero-shot-image-classification
Traceback (most recent call last):
  File "/raid/lingo/alachyan/anaconda3/envs/fan_trt/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/raid/lingo/alachyan/anaconda3/envs/fan_trt/lib/python3.9/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/raid/lingo/alachyan/anaconda3/envs/fan_trt/lib/python3.9/site-packages/optimum/commands/export/onnx.py", line 232, in run
    main_export(
  File "/raid/lingo/alachyan/anaconda3/envs/fan_trt/lib/python3.9/site-packages/optimum/exporters/onnx/__main__.py", line 323, in main_export
    model = TasksManager.get_model_from_task(
  File "/raid/lingo/alachyan/anaconda3/envs/fan_trt/lib/python3.9/site-packages/optimum/exporters/tasks.py", line 1683, in get_model_from_task
    model_class = TasksManager.get_model_class_for_task(
  File "/raid/lingo/alachyan/anaconda3/envs/fan_trt/lib/python3.9/site-packages/optimum/exporters/tasks.py", line 1148, in get_model_class_for_task
    tasks_to_model_loader = TasksManager._LIBRARY_TO_TASKS_TO_MODEL_LOADER_MAP[library]
KeyError: 'open_clip' 

### Expected behavior

Getting key_error for exporting onnx model based on the open_clip library. Seems that the `TasksManager._LIBRARY_TO_TASKS_TO_MODEL_LOADER_MAP` map does not have open_clip integrated. 

Open AI CLIP exporting working as expected without any problems. 

` % optimum-cli export onnx -m openai/clip-vit-base-patch32 --framework pt ./clip.onnx`

**Comment by fxmarty** [comment]
Hi @alachyan-ml, thank you for the report!

I run

```
optimum-cli export onnx -m openai/clip-vit-base-patch32 --framework pt clip_onnx
```

with

```
torch==2.1.0
optimum==1.13.2
transformers==4.34.0
```

and can not reproduce this issue. Could you give more details about the issue you are facing?

**Comment by isaac-chung** [comment]
@fxmarty the model in your example is from PpenAI's clip, but not [open_clip](https://github.com/mlfoundations/open_clip). I ran
```
optimum-cli export onnx -m laion/CLIP-ViT-B-32-laion2B-s34B-b79K --framework pt clip_onnx
```
with
```
optimum==1.13.2
torch==2.0.0
transformers==4.34.0
```
and got the same error message as @alachyan-ml did.

**Comment by fxmarty** [comment]
Hi @isaac-chung, I used the model id `openai/clip-vit-base-patch32` shared by @alachyan-ml: https://github.com/huggingface/optimum/issues/1450#issue-1943412047

Let me have a look at `laion/CLIP-ViT-B-32-laion2B-s34B-b79K` and get back to you.

**Comment by isaac-chung** [comment]
@fxmarty it doesn't seem like @alachyan-ml actually provided the command they ran, as they only mentioned that the open AI one works with no issue, which we confirmed 👌 

> Open AI CLIP exporting working as expected without any problems. 
` % optimum-cli export onnx -m openai/clip-vit-base-patch32 --framework pt ./clip.onnx`

Thanks for taking a look! I started poking around and tried adding the following, still WIP with no success yet:
in class TasksManager:
```diff
+        _OPEN_CLIP_TASKS_TO_MODEL_LOADERS = {
+            "zero-shot-image-classification": "create_model_and_transforms",
+        }

        _LIBRARY_TO_TASKS_TO_MODEL_LOADER_MAP = {
            "transformers": _TRANSFORMERS_TASKS_TO_MODEL_LOADERS,
            "diffusers": _DIFFUSERS_TASKS_TO_MODEL_LOADERS,
            "timm": _TIMM_TASKS_TO_MODEL_LOADERS,
+            "open_clip": _OPEN_CLIP_TASKS_TO_MODEL_LOADERS,
        }
```

In TasksManager.get_model_from_task:
```diff
+        if library_name == "open_clip":
+            model, _, _ = model_class(f"hf-hub:{model_name_or_path}", cache_dir=cache_dir)
+            TasksManager.standardize_model_attributes(
+                model_name_or_path, model, subfolder, revision, cache_dir, library_name
+            )
+            return model
```

**Comment by isaac-chung** [comment]
I could gather these into a PR and maybe we could continue the discussion for the fix there?

**Comment by fxmarty** [comment]
For sure, thank you @isaac-chung!

**Comment by alachyan-ml** [comment]
Hi, sorry was away for a few days, but @isaac-chung is correct. I forgot to include the command that yielded the error but the laion/CLIP-ViT-B-32-laion2B-s34B-b79K model is the one I was trying to export. Took a look at the thread and seems like it is being looked at. Thanks!

**Comment by nemphys** [comment]
Hi, any news on this one? I was trying to convert the same model (CLIP-ViT-B-32-laion2B-s34B-b79K) with the exact same error.

**Comment by sushilkhadkaanon** [comment]
Hi @alachyan-ml , @nemphys , @fxmarty , @isaac-chung , Did any one you found a way to export open_clip to onnx?

**Comment by alachyan-ml** [comment]
Hey, picking this up again let me take a look.
