### ISSUE TITLE
Bloom failing after setting up max_position_embeddings on Trainer.py

### ISSUE THREAD

**Issue by AdamLouly** [huggingface/optimum#1477]
### System Info

```shell
optimum nightly, ort nightly.
```

### Who can help?

We're encountering an issue with Bloom after merging the PR found here: https://github.com/huggingface/optimum/pull/1335. In this PR, we set up block_size to config.max_position_embeddings, assuming that all configs will have max_position_embeddings. 

`Traceback (most recent call last):
  File "/workspace/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 657, in <module>
    main()
  File "/workspace/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 498, in main
    if block_size > config.max_position_embeddings:
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers-4.35.0.dev0-py3.8.egg/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BloomConfig' object has no attribute 'max_position_embeddings'`

However, it seems that bloomConfig does not have this attribute.

You can find the bloomConfig definition here: https://github.com/huggingface/transformers/blob/v4.34.1/src/transformers/models/bloom/configuration_bloom.py

This issue can appear whenever transformers added a new model configs without that attribute.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

torchrun --nproc-per-node=4 run_clm.py --model_name_or_path bigscience/bloom-560m --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --do_train --do_eval --per_device_train_batch_size 32 --num_train_epochs 3 --overwrite_output_dir --output_dir ./outputs/ --per_device_eval_batch_size 32 --seed 1337 --fp16 True --learning_rate 2e-5 --optim adamw_ort_fused

### Expected behavior

Traceback (most recent call last):
  File "/workspace/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 657, in <module>
    main()
  File "/workspace/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 498, in main
    if block_size > config.max_position_embeddings:
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers-4.35.0.dev0-py3.8.egg/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BloomConfig' object has no attribute 'max_position_embeddings'

**Comment by AdamLouly** [comment]
this should fix it https://github.com/huggingface/optimum/pull/1478
