### ISSUE TITLE
feature_extractor for stabilityai/sdxl-turbo is None

### ISSUE THREAD

**Issue by satsumas** [huggingface/optimum#1588]
### System Info

I am trying to compile `stabilityai/sdxl-turbo` for Inferentia inf2. 

I used the optimum CLI to export to neuron, using `optimum-cli export neuron -m stabilityai/sdxl-turbo --batch_size 1 --height 512 --width 512  models/checkpoints`, which produced the following exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/repos/InternalForkComfyUI/inf2_venv/lib/python3.8/site-packages/optimum/exporters/neuron/__main__.py", line 342, in <module>
    main()
  File "/home/ubuntu/repos/InternalForkComfyUI/inf2_venv/lib/python3.8/site-packages/optimum/exporters/neuron/__main__.py", line 327, in main
    main_export(
  File "/home/ubuntu/repos/InternalForkComfyUI/inf2_venv/lib/python3.8/site-packages/optimum/exporters/neuron/__main__.py", line 240, in main_export
    model.feature_extractor.save_pretrained(output.joinpath("feature_extractor"))
AttributeError: 'NoneType' object has no attribute 'save_pretrained'
Traceback (most recent call last):
  File "/home/ubuntu/repos/InternalForkComfyUI/inf2_venv/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/repos/InternalForkComfyUI/inf2_venv/lib/python3.8/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/home/ubuntu/repos/InternalForkComfyUI/inf2_venv/lib/python3.8/site-packages/optimum/commands/export/neuronx.py", line 155, in run
    subprocess.run(full_command, shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.neuron -m stabilityai/sdxl-turbo --batch_size 1 --height 512 --width 512 models/checkpoints' returned non-zero exit status 1.
```

The lines responsible for the error (239-240 of optimum/exporters/neuron/__main__.py) check whether the model has attribute `feature_extractor`:

```
if hasattr(model, "feature_extractor"):
     model.feature_extractor.save_pretrained(output.joinpath("feature_extractor"))
```

Digging into that model, I can see that it does have a `feature_extractor` attribute, which is set to `None`, causing the exception above. I tried removing the relevant lines from my local optimum package. This allows the model to compile as expected.

The compiled mode does fail validation however, although just by a small amount. I suspect this is unrelated to my change above, but just in case, I'll reproduce the error here. I compiled on inf2.8xlarge:

```
Validating text_encoder model...
        - Validating Neuron Model output "last_hidden_state":
                -[✓] (1, 77, 768) matches (1, 77, 768)
                -[x] values not close enough, max diff: 0.0012068748474121094 (atol: 0.001)
        - Validating Neuron Model output "pooler_output":
                -[✓] (1, 768) matches (1, 768)
                -[✓] all values close (atol: 0.001)
        - Validating Neuron Model output "hidden_states":
                -[✓] (13, 1, 77, 768) matches (13, 1, 77, 768)
                -[✓] all values close (atol: 0.001)
The maximum absolute difference between the output of the reference model and the Neuron exported model is not within the set tolerance 0.001:
- last_hidden_state: max diff = 0.0012068748474121094
Validating text_encoder_2 model...
        - Validating Neuron Model output "text_embeds":
                -[✓] (1, 1280) matches (1, 1280)
                -[✓] all values close (atol: 0.001)
        - Validating Neuron Model output "last_hidden_state":
                -[✓] (1, 77, 1280) matches (1, 77, 1280)
                -[x] values not close enough, max diff: 0.002083510160446167 (atol: 0.001)
        - Validating Neuron Model output "hidden_states":
                -[✓] (33, 1, 77, 1280) matches (33, 1, 77, 1280)
                -[x] values not close enough, max diff: 0.0016384124755859375 (atol: 0.001)
The maximum absolute difference between the output of the reference model and the Neuron exported model is not within the set tolerance 0.001:
- last_hidden_state: max diff = 0.002083510160446167
- hidden_states: max diff = 0.0016384124755859375
Validating unet model...
Validating vae_decoder model...
        -[✓] Neuron model output names match reference model (sample)
        - Validating Neuron Model output "sample":
                -[✓] (1, 3, 512, 512) matches (1, 3, 512, 512)
                -[✓] all values close (atol: 0.001)
An error occured with the error message: Validation of unet fails: Unknown opcode for unpickling at 0: 0.
 The exported model was saved at: models/checkpoints
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

1. Set up inf2 instance on Ubuntu 20, using the guide https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/pytorch/neuronx/ubuntu/torch-neuronx-ubuntu20.html#setup-torch-neuronx-ubuntu20

2. `pip install optimum==1.15.0, optimum-neuron==0.0.13`

3. `mkdir models`
`mkdir models/checkpoints`
`optimum-cli export neuron -m stabilityai/sdxl-turbo --batch_size 1 --height 512 --width 512  models/checkpoints`

3. The compilation fails with the error above.

### Expected behavior

I would expect the Huggingface model stabilityai/sdxl-turbo to compile

**Comment by satsumas** [comment]
I'm going to close this issue and discuss it on the  https://github.com/huggingface/optimum-neuron repo.
