### ISSUE TITLE
Converting owlvit model into onnx format

### ISSUE THREAD

**Issue by solomonmanuelraj** [huggingface/optimum#1633]
### System Info

```shell
Hi Team,

Need your help to convert owl-vit model (OwlViTForObjectDetection) into onnx file.

##########################################################################################
from PIL import Image
from transformers import OwlViTProcessor, OwlViTForObjectDetection

model_id = "google/owlvit-base-patch16"
owlbit8_model = OwlViTForObjectDetection.from_pretrained(model_id,device_map="auto",load_in_8bit=True)
owlbit8_model.save_pretrained("local file system - dir path",
save_config=True, safe_serialization=True)

#########################################################################################

Output in the local file system - dir path
config.json
model.safetensors

#########################################################################################

optimum-cli export onnx --model 'local file system - dir path' --task 'zero-shot-object-detection' --framework 'pt' output_dir

###########################################################################################
receiving the following error msgs.

##########################################################################################

Using the export variant default. Available variants are:

default: The default ONNX variant.
Using framework PyTorch: 2.1.0
Traceback (most recent call last):
File "/home/..../miniconda3/envs/testenv/bin/optimum-cli", line 8, in
sys.exit(main())
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
service.run()
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/optimum/commands/export/onnx.py", line 246, in run
main_export(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/onnx/main.py", line 551, in main_export
_, onnx_outputs = export_models(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/onnx/convert.py", line 753, in export_models
export(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/onnx/convert.py", line 856, in export
export_output = export_pytorch(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/onnx/convert.py", line 573, in export_pytorch
onnx_export(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
_export(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1596, in _export
graph, params_dict, torch_out = _model_to_graph(
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
graph, params, torch_out, module = _create_jit_graph(model, args)
File "/home..../miniconda3/envs/testenv/lib/python3.10/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
graph, torch_out = _trace_and_get_graph_from_model(model, args)
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/torch/onnx/utils.py", line 907, in _trace_and_get_graph_from_model
orig_state_dict_keys = torch.jit._unique_state_dict(model).keys()
File "/home/..../miniconda3/envs/testenv/lib/python3.10/site-packages/torch/jit/_trace.py", line 76, in _unique_state_dict
filtered_dict[k] = v.detach()
AttributeError: 'str' object has no attribute 'detach'
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

it gives filtered_dict[k] = v.detach()
AttributeError: 'str' object has no attribute 'detach'

### Expected behavior

onnx file

**Comment by fxmarty** [comment]
Hi @solomonmanuelraj, the following is working:

```python
from PIL import Image
from transformers import OwlViTProcessor, OwlViTForObjectDetection

model_id = "google/owlvit-base-patch16"
owlbit8_model = OwlViTForObjectDetection.from_pretrained(model_id, device_map="auto", load_in_8bit=False)
owlbit8_model.save_pretrained("owlvit", save_config=True, safe_serialization=False)
```

and `optimum-cli export onnx -m owlvit --task 'zero-shot-object-detection' --framework 'pt' owlvit_onnx`.

Note that bitsandbytes modules (like `Linear8bitLt`) can currently not be exported to ONNX.

Using `safe_serialization=True` + `device_map="auto"` does not work for me.

**Comment by fxmarty** [comment]
Thank you @solomonmanuelraj. `load_in_8bit=True` is not the only option available to use quantization. This argument specifically uses the quantization scheme from the bitsandbytes library, which can not be exported to ONNX from PyTorch. Reference for this: https://huggingface.co/blog/hf-bitsandbytes-integration

An alternative for you could be to use a classic A8W8 dynamic quantization scheme (all activations on 8 bits, all weights on 8 bits), using ONNX Runtime quantizer available through Optimum:

```
optimum-cli export onnx -m google/owlvit-base-patch16 --task 'zero-shot-object-detection' --framework 'pt' owlvit_onnx
optimum-cli onnxruntime quantize --onnx_model owlvit_onnx --avx512 -o owlvit_onnx_quantized --per_channel
```

reducing the model size to ~155 MB. However, you still need to validate the accuracy of the quantized model. Note that this command line by default quantizes **all** possible ops (https://github.com/microsoft/onnxruntime/blob/7cb8b20db2d329cf67e170293b2d2c81213e6100/onnxruntime/python/tools/quantization/registry.py#L26-L86), which may be too aggressive. This can be customized when doing the export programmatically (example in the link below).

References: https://huggingface.co/docs/optimum/main/en/concept_guides/quantization & https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/quantization

**Comment by fxmarty** [comment]
@solomonmanuelraj I see. I am not sure about your problem. If at the end of the day your goal is to obtain a quantized ONNX model, your best bet would probably be:

1. Do fine-tuning / parameter efficient fine-tuning
2. Merge adapter weights in the original model
3. ONNX export
4. Quantization using ORT quantization tools

If quantization was simulated in steps 1/2, you would need to make sure that the quantization scheme used by ORT is not completely different than what is used during QAT.

**Comment by fxmarty** [comment]
Hi @solomonmanuelraj, if you use optimum dev branch (cloning from github and installing locally), this is fixed with https://github.com/huggingface/optimum/pull/1650. You will be able to export the model with an opset lower than what is specified in the onnx configuration.
