### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ShilpaSangappa** [huggingface/optimum#174]
I have Python 3.6.9 and i get the following installation issues.

```
(venv_hf_optimum)$ pip install "optimum[onnxruntime]==1.2.0"
Collecting optimum[onnxruntime]==1.2.0
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement optimum[onnxruntime]==1.2.0 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2a0, 0.1.2, 0.1.3, 1.0.0, 1.1.0, 1.1.1)
No matching distribution found for optimum[onnxruntime]==1.2.0
```

```
(venv_hf_optimum)$ python -m pip install optimum
Collecting optimum
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/a5/05/4f31c8ff3b01f8d99a6352528d221210341bf4b38859e8747cfc19c5cd9d/optimum-1.1.1.tar.gz (66kB)
    100% |████████████████████████████████| 71kB 755kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vwtwg4zk/optimum/setup.py", line 3, in <module>
        from setuptools import find_namespace_packages, setup
    ImportError: cannot import name 'find_namespace_packages'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vwtwg4zk/optimum/
```

**Comment by ShilpaSangappa** [comment]
Following steps let me install optimum, without errors:

```
$ virtualenv -p /usr/bin/python3.7 onnx_venv
$ source onnx_venv/bin/activate
(onnx_venv) $ pip install onnx==1.10.0
(onnx_venv) $ pip install onnxruntime==1.10.0
(onnx_venv) $ python -m pip install optimum

```
But post installation, I see following errors:

```
(onnx_venv) $ python
Python 3.7.5 (default, Dec  9 2021, 17:04:37) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AutoTokenizer, pipeline
>>> from optimum.onnxruntime import ORTModelForSeq2SeqLM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datadrive/shilpa/work/github/huggingface_2/onnx_venv/lib/python3.7/site-packages/optimum/onnxruntime/__init__.py", line 51, in <module>
    from .configuration import ORTConfig
  File "/datadrive/shilpa/work/github/huggingface_2/onnx_venv/lib/python3.7/site-packages/optimum/onnxruntime/configuration.py", line 20, in <module>
    from datasets import Dataset
ModuleNotFoundError: No module named 'datasets'
>>> 

```

**Comment by fxmarty** [comment]
Looks like support for Python <3.8 was dropped in https://github.com/huggingface/optimum/commit/a31e59eddafc53f6146a4850ffe91d4cfc00c0a6, see https://github.com/huggingface/optimum/blob/main/setup.py#L75 . I have no issue with `pip install optimum[onnxruntime]==1.2.0` on Python 3.8. Is this a problem to you?

For the last issue, I think it is because `datasets` is installed through `pip install optimum[onnxruntime]` but not with `pip install optimum`. @mfuntowicz Shoud we put `datasets` as a global dependency https://github.com/huggingface/optimum/blob/800e01c466917570c68812f91722df24a6ab82b0/setup.py#L15 ?

**Comment by philschmid** [comment]
@ShilpaSangappa could you try installing it with `python3.8` or greater? 

>  but not with pip install optimum. @mfuntowicz Should we put datasets as a global dependency

`datasets` is currently feature specific so need to have it as a global dependency

**Comment by fxmarty** [comment]
Yes, looks like all `onnxruntime`, `onnxruntime-gpu`, `intel`, `graphcore` and `habana` require `datasets`. Only the tests don't.

**Comment by philschmid** [comment]
Nice @ShilpaSangappa. 

We are also working on adding support for Python 3.7 back
* https://github.com/huggingface/optimum/pull/176#pullrequestreview-969298043
