### ISSUE TITLE
List index out of range when trying to export with openvino

### ISSUE THREAD

**Issue by talkhaldi** [huggingface/optimum#1765]
### System Info

```shell
OS: Ubuntu 22.04.2 LTS
Python: 3.10.6
Packages:
optimum==1.17.1 (also tried 1.18.0.dev0, 1.16.2)
optimum-intel==1.15.2
openvino==2024.0.0 (also tried 2023.3.0)
transformers==4.38.2 (also tried 4.39.0, 4.37.2)
```

### Who can help?

@michaelbenayoun  It seems you're the expert in converting models. I hope you help me with this issue!

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Simply trying to convert with:
`optimum-cli export openvino --model intfloat/multilingual-e5-large ov_e5-large` 

gives the following error:
```
Framework not specified. Using pt to export the model.
Automatic task detection to feature-extraction (possible synonyms are: default, mask-generation, sentence-similarity). 
Using the export variant default. Available variants are: 
                - default: The default ONNX variant. 
Using framework PyTorch: 2.2.1+cu121
Overriding 1 configuration item(s)
       - use_cache -> False
 /home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/transformers/modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
    warnings.warn(
Traceback (most recent call last): 
  File "/home/ubuntu/anaconda3/envs/testenv/bin/optimum-cli", line 8, in <module>
    sys.exit(main()) 
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/commands/export/openvino.py", line 148, in run
    main_export(
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/openvino/__main__.py", line 292, in main_export
    export_from_model(
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/openvino/convert.py", line 694, in export_from_model
    export_models(
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/openvino/convert.py", line 518, in export_models
    export(
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/openvino/convert.py", line 168, in export
    return export_pytorch(
  File "/home/ubuntu/anaconda3/envs/testenv/lib/python3.10/site-packages/optimum/exporters/openvino/convert.py", line 441, in export_pytorch
    inp_data = flatten_inputs[idx]
IndexError: list index out of range
```

I also tried other models: `intfloat/multilingual-e5-base` and `pkshatech/GLuCoSE-base-ja` with the same problem.

### Expected behavior

It's supposed to produce a model converted to OpenVINO format

**Comment by michaelbenayoun** [comment]
cc @echarlaix
