### ISSUE TITLE
HF_HUB_OFFLINE not supported

### ISSUE THREAD

**Issue by agix** [huggingface/optimum#1796]
### System Info

```shell
optimum 1.18.0 python 3.11.7
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```python
from optimum.onnxruntime import ORTModelForFeatureExtraction
ORTModelForFeatureExtraction.from_pretrained('hf-internal-testing/tiny-random-BertModel', subfolder='onnx')
```

Run a first time with this command: `HF_HOME=/tmp/ python test_offline.py`

It should download the model in /tmp/

Then run `HF_HUB_OFFLINE=1 HF_HOME=/tmp/ python test_offline.py`

It will retry to download it and throw:

```
Traceback (most recent call last):
  File "/home/agix/git/optimum/test_offline.py", line 2, in <module>
    ORTModelForFeatureExtraction.from_pretrained('hf-internal-testing/tiny-random-BertModel', subfolder='onnx')
  File "/home/agix/git/optimum/optimum/onnxruntime/modeling_ort.py", line 663, in from_pretrained
    return super().from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/git/optimum/optimum/modeling_base.py", line 403, in from_pretrained
    return from_pretrained_method(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/git/optimum/optimum/onnxruntime/modeling_ort.py", line 474, in _from_pretrained
    repo_files = map(Path, HfApi().list_repo_files(model_id, revision=revision, token=token))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2787, in list_repo_files
    return [
           ^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2787, in <listcomp>
    return [
           ^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2923, in list_repo_tree
    for path_info in paginate(path=tree_url, headers=headers, params={"recursive": recursive, "expand": expand}):
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/huggingface_hub/utils/_pagination.py", line 36, in paginate
    r = session.get(path, params=params, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agix/.local/share/virtualenvs/optimum-SeLC1sUZ/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 79, in send
    raise OfflineModeIsEnabled(
huggingface_hub.utils._http.OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/hf-internal-testing/tiny-random-BertModel/tree/main?recursive=True&expand=False: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.
```

### Expected behavior

It should use the cached model and not throw.

The error class is not the correct one here:
https://github.com/huggingface/optimum/blob/253c6c2ff0f834b6fb03557add6ba4ae1272714d/optimum/exporters/tasks.py#L1388

`except (RequestsConnectionError, huggingface_hub.utils._http.OfflineModeIsEnabled) as e:  # Hub not accessible`

But then `cache_dir` is default overrided with `None` instead of using `huggingface_hub.constants.HUGGINGFACE_HUB_CACHE` in various places like https://github.com/huggingface/optimum/blob/253c6c2ff0f834b6fb03557add6ba4ae1272714d/optimum/modeling_base.py#L320

So the cache folder is not properly used.

And finally it calls `list_repo_files` again without error handling at all here

https://github.com/huggingface/optimum/blob/253c6c2ff0f834b6fb03557add6ba4ae1272714d/optimum/onnxruntime/modeling_ort.py#L474

I'm not sure what's the best way to fix it so I preferred to open a bug than a PR

**Comment by fxmarty** [comment]
Thank you, will fix shortly

**Comment by fxmarty** [comment]
@agix @naddeoa Thank you for reporting the issue, this should be fixed on main with https://github.com/huggingface/optimum/pull/1805, could you give a second try? This should make it in the next patch or release, hopefully soon.

**Comment by agix** [comment]
It seems to work for me ! Thank you very much !
