### ISSUE TITLE
Tried to train using run_glue.py but it threw an ImportError

### ISSUE THREAD

**Issue by nirmal2k** [huggingface/optimum#187]
I tried to train a text classification model using [run_glue.py](https://github.com/huggingface/optimum/blob/main/examples/onnxruntime/training/text-classification/run_glue.py) using 
```
python run_glue.py \
    --model_name_or_path bert-base-uncased \
    --task_name sst2 \
    --do_train \
    --do_eval \
    --output_dir /tmp/ort-bert-sst2/
```

I get the below error:
```
Traceback (most recent call last):
  File "run_glue.py", line 571, in <module>
    main()
  File "run_glue.py", line 490, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/optimum/onnxruntime/trainer.py", line 295, in train
    model = ORTModule(self.model)
  File "/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/ortmodule.py", line 90, in __init__
    self._fallback_manager.handle_exception(exception=e,
  File "/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_fallback.py", line 151, in handle_exception
    raise exception
  File "/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/ortmodule.py", line 66, in __init__
    raise ortmodule._FALLBACK_INIT_EXCEPTION
  File "/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_fallback_exceptions.py", line 72, in wrap_exception
    raise new_exception(raised_exception) from raised_exception
onnxruntime.training.ortmodule._fallback_exceptions.ORTModuleInitException: ORTModule's extensions were not detected at '/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions' folder. Run `python -m torch_ort.configure` before using `ORTModule` frontend.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/cpu/torch_interop_utils/__init__.py", line 3, in clear_all_grad_fns
    from onnxruntime.training.ortmodule.torch_cpp_extensions import torch_interop_utils
ImportError: cannot import name 'torch_interop_utils' from 'onnxruntime.training.ortmodule.torch_cpp_extensions' (/home/nirmal/miniconda3/envs/optimum/lib/python3.8/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/__init__.py)
```

**Comment by nirmal2k** [comment]
Ran "python -m torch_ort.configure" to fix. This fix is provided in the error itself.
