### ISSUE TITLE
SentenceTransformer to tflite export failure

### ISSUE THREAD

**Issue by TalonBvV** [huggingface/optimum#1982]
### System Info

```shell
Please see below the two commands I tried to use.

1) optimum-cli export tflite --model BAAI/bge-m3  --quantize int8-dynamic --sequence_length 2048 --batch_size 10 bge-m3-tflite/

2) python -m optimum.exporters.tflite --model BAAI/bge-m3 --quantize int8-dynamic --sequence_length 2048 --batch_size 10 bge-m3-tflite/

Here is the error I get:

Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\lib\site-packages\optimum\exporters\tflite\__main__.py", line 146, in <module>
    main()
  File "C:\Python\lib\site-packages\optimum\exporters\tflite\__main__.py", line 61, in main
    model = TasksManager.get_model_from_task(
  File "C:\Python\lib\site-packages\optimum\exporters\tasks.py", line 1786, in get_model_from_task
    model_class = TasksManager.get_model_class_for_task(
  File "C:\Python\lib\site-packages\optimum\exporters\tasks.py", line 1239, in get_model_class_for_task
    tasks_to_model_loader = TasksManager._LIBRARY_TO_TF_TASKS_TO_MODEL_LOADER_MAP[library]
KeyError: 'sentence_transformers'
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

1) optimum-cli export tflite --model BAAI/bge-m3  --quantize int8-dynamic --sequence_length 2048 --batch_size 10 bge-m3-tflite/

2) python -m optimum.exporters.tflite --model BAAI/bge-m3 --quantize int8-dynamic --sequence_length 2048 --batch_size 10 bge-m3-tflite/

### Expected behavior

I expect it to export the tflite model.

**Comment by TalonBvV** [comment]
Here are my dependency versions:
1) optimum version: 1.21.2
2) python version: 3.12
3) tensorflow version: 2.17.0

**Comment by TalonBvV** [comment]
I have repeated my export process in colab and the result is the same.
