### ISSUE TITLE
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))

### ISSUE THREAD

**Issue by talhaanwarch** [huggingface/optimum#223]
### System Info

```shell
onnx==1.12.0
onnxruntime==1.11.1
optimum==1.2.3
python 3.8.8
Windows 11
```

### Who can help?

@JingyaHuang, @echarlaix

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Copied the exact code from github readme, the code is working on linux enviroment, but failed on windows 

```
from optimum.onnxruntime.configuration import AutoQuantizationConfig
from optimum.onnxruntime import ORTQuantizer

# The model we wish to quantize
model_checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
# The type of quantization to apply
qconfig = AutoQuantizationConfig.arm64(is_static=False, per_channel=False)
quantizer = ORTQuantizer.from_pretrained(model_checkpoint, feature="sequence-classification")

# Quantize the model!
quantizer.export(
    onnx_model_path="model.onnx",
    onnx_quantized_model_output_path="model-quantized.onnx",
    quantization_config=qconfig,
)


from functools import partial
from datasets import Dataset
from optimum.onnxruntime.model import ORTModel

# Load quantized model
ort_model = ORTModel("model-quantized.onnx", quantizer._onnx_config)
# Create a dataset or load one from the Hub
ds = Dataset.from_dict({"sentence": ["I love burritos!"]})
# Tokenize the inputs
def preprocess_fn(ex, tokenizer):
    return tokenizer(ex["sentence"])

tokenized_ds = ds.map(partial(preprocess_fn, tokenizer=quantizer.tokenizer))
ort_outputs = ort_model.evaluation_loop(tokenized_ds)
# Extract logits!
ort_outputs.predictions
```
Traceback
```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    ort_outputs = ort_model.evaluation_loop(tokenized_ds)
  File "D:\facebook_Senti\venv\lib\site-packages\optimum\onnxruntime\model.py", line 98, in evaluation_loop
    preds = session.run(self.onnx_named_outputs, onnx_inputs)
  File "D:\facebook_Senti\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))
```

### Expected behavior

```shell
Code working on Linux but failed on windows
```

**Comment by talhaanwarch** [comment]
Related issue: https://github.com/huggingface/transformers/issues/15575

**Comment by echarlaix** [comment]
Hi @talhaanwarch , 

It seems that the inference session is expecting elements of int64 data type.

Can you try :
```python
onnx_inputs = {key: np.array([inputs[key]], dtype=np.int64) for key in self.onnx_config.inputs if key in inputs}
```

Also [`ORTModel`](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/model.py#L34) was a class added for users to be able to obtain the evaluation results in order to compare their original model with the resulting optimized / quantized model, and was meant to be temporary. This class is now depreciated and we encourage users to use our new classes [`ORTModelForXxx`](https://huggingface.co/docs/optimum/onnxruntime/modeling_ort#switching-from-transformers-to-optimum-inference).
