### ISSUE TITLE
[ERROR] Unexpected exception RuntimeError('Expect weight, indices, and offsets to be contiguous.') happened during tuning. When trying to apply static quantization to a 'roberta-base' model

### ISSUE THREAD

**Issue by StMarou** [huggingface/optimum#292]
### System Info

```shell
optimum[intel] version: 1.2.3
python version: 3.7.13
transformers version: 4.20.1
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

To reproduce this error just change the checkpoint variable to 'roberta-base' in https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/text_classification_quantization_inc.ipynb

### Expected behavior

I am trying to apply static quantization to a RoBERTa based model from huggingface. When I run the [colab notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/text_classification_quantization_inc.ipynb) with roberta as the base model , the following error arises:
````
```
The following columns in the training set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: idx, sentence1, sentence2. If idx, sentence1, sentence2 are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
2022-07-13 11:23:59 [INFO] Start sequential pipeline execution.
2022-07-13 11:23:59 [INFO] The 0th step being executing is QUANTIZATION.
2022-07-13 11:24:00 [INFO] Pass query framework capability elapsed time: 750.14 ms
2022-07-13 11:24:00 [INFO] Get FP32 model baseline.
The following columns in the evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: idx, sentence1, sentence2. If idx, sentence1, sentence2 are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 277
  Batch size = 16
 [17/17 03:45]
2022-07-13 11:25:44 [INFO] Save tuning history to /content/nc_workspace/2022-07-13_11-13-18/./history.snapshot.
2022-07-13 11:25:44 [INFO] FP32 baseline is: [Accuracy: 0.4779, Duration (seconds): 104.4110]
/usr/local/lib/python3.7/dist-packages/torch/ao/quantization/qconfig.py:92: UserWarning: QConfigDynamic is going to be deprecated in PyTorch 1.12, please use QConfig instead
  warnings.warn("QConfigDynamic is going to be deprecated in PyTorch 1.12, please use QConfig instead")
2022-07-13 11:25:45 [INFO] Fx trace of the entire model failed, We will conduct auto quantization
/usr/local/lib/python3.7/dist-packages/torch/ao/quantization/observer.py:178: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  reduce_range will be deprecated in a future release of PyTorch."
2022-07-13 11:25:47 [WARNING] Please note that calibration sampling size 100 isn't divisible exactly by batch size 16. So the real sampling size is 112.
/usr/local/lib/python3.7/dist-packages/torch/nn/quantized/_reference/modules/utils.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(weight_qparams["scale"], dtype=torch.float, device=device))
/usr/local/lib/python3.7/dist-packages/torch/nn/quantized/_reference/modules/utils.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(weight_qparams["zero_point"], dtype=zero_point_dtype, device=device))
2022-07-13 11:26:46 [INFO] |*********Mixed Precision Statistics********|
2022-07-13 11:26:46 [INFO] +---------------------+-------+------+------+
2022-07-13 11:26:46 [INFO] |       Op Type       | Total | INT8 | FP32 |
2022-07-13 11:26:46 [INFO] +---------------------+-------+------+------+
2022-07-13 11:26:46 [INFO] |      Embedding      |   3   |  3   |  0   |
2022-07-13 11:26:46 [INFO] |      LayerNorm      |   25  |  0   |  25  |
2022-07-13 11:26:46 [INFO] | quantize_per_tensor |   74  |  74  |  0   |
2022-07-13 11:26:46 [INFO] |        Linear       |   74  |  74  |  0   |
2022-07-13 11:26:46 [INFO] |      dequantize     |   74  |  74  |  0   |
2022-07-13 11:26:46 [INFO] |     input_tensor    |   24  |  24  |  0   |
2022-07-13 11:26:46 [INFO] |       Dropout       |   26  |  0   |  26  |
2022-07-13 11:26:46 [INFO] +---------------------+-------+------+------+
2022-07-13 11:26:46 [INFO] Pass quantize model elapsed time: 61737.12 ms
The following columns in the evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: idx, sentence1, sentence2. If idx, sentence1, sentence2 are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 277
  Batch size = 16
2022-07-13 11:26:46 [ERROR] Unexpected exception RuntimeError('Expect weight, indices, and offsets to be contiguous.') happened during tuning.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/neural_compressor/experimental/quantization.py", line 151, in execute
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/neural_compressor/strategy/strategy.py", line 401, in traverse
    self.last_tune_result = self._evaluate(self.last_qmodel)
  File "/usr/local/lib/python3.7/dist-packages/neural_compressor/strategy/strategy.py", line 506, in _evaluate
    self.eval_func, model if self.framework == "pytorch_ipex" else model.model
  File "/usr/local/lib/python3.7/dist-packages/neural_compressor/objective.py", line 266, in evaluate
    acc = eval_func(model)
  File "<ipython-input-39-368c7d092791>", line 5, in eval_func
    metrics = trainer.evaluate()
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 2628, in evaluate
    metric_key_prefix=metric_key_prefix,
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 2798, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 3039, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 2377, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/roberta/modeling_roberta.py", line 1215, in forward
    return_dict=return_dict,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/roberta/modeling_roberta.py", line 846, in forward
    past_key_values_length=past_key_values_length,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/roberta/modeling_roberta.py", line 129, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/usr/local/lib/python3.7/dist-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.1019", line 6, in forward
    module = self.module(x);  x = None
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/quantized/modules/embedding_ops.py", line 116, in forward
    return torch.ops.quantized.embedding_byte(self._packed_params._packed_weight, indices)
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Expect weight, indices, and offsets to be contiguous.
2022-07-13 11:26:46 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.
```
````

**Comment by philschmid** [comment]
cc @echarlaix

**Comment by echarlaix** [comment]
Hi @StMarou, thanks for reporting this issue, it will be fixed in [#12](https://github.com/huggingface/optimum-intel/pull/12)
