### ISSUE TITLE
KeyError: Unknown task: summarization

### ISSUE THREAD

**Issue by zeke-john** [huggingface/optimum#340]
### System Info

```shell
onnx - 1.12.0
onnxruntime - 1.12.1
optimum - 1.3.0
transformers - 4.21.1
torch - 1.10.2
python 3.8.6
```

### Who can help?

@JingyaHuang, @philschmid

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am following the [quickstart](https://github.com/huggingface/optimum#quickstart) on this github, except i'm trying to change the task from `sequence-classification` to `summarization`, with the [`facebook/bart-large-cnn`](https://huggingface.co/facebook/bart-large-cnn) model. So i first exported the model to the ONNX format, which worked fine,

Code:

    import os
    from pathlib import Path
    from optimum.onnxruntime import ORTModelForSeq2SeqLM
    from transformers import AutoTokenizer

    model_checkpoint = "facebook/bart-large-cnn"
    save_directory = Path('onnx')
    file_name = "model.onnx"
    onnx_path = os.path.join(save_directory, "model.onnx")

    # Load a model from transformers and export it through the ONNX format
    model = ORTModelForSeq2SeqLM.from_pretrained(model_checkpoint, from_transformers=True)
    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_cdn=True)

    # Save the onnx model and tokenizer
    model.save_pretrained(save_directory, file_name=file_name)
    tokenizer.save_pretrained(save_directory)

and then when i tried to apply dynamic quantization, or optimization with the ONNX Runtime in this case, using this code:

    from pathlib import Path
    from transformers import AutoTokenizer, pipeline
    from optimum.onnxruntime import ORTModelForSeq2SeqLM, ORTOptimizer
    from optimum.onnxruntime.configuration import OptimizationConfig

    model_id = "facebook/bart-large-cnn"
    onnx_path = Path("onnx")
    task = "summarization"

    optimizer = ORTOptimizer.from_pretrained(model_id, feature=task)
    optimization_config = OptimizationConfig(optimization_level=99) 

    optimizer.export(
        onnx_model_path=onnx_path / "model.onnx",
        onnx_optimized_model_output_path=onnx_path / "model-optimized.onnx",
        optimization_config=optimization_config,
    )

i get the error:
`Traceback (most recent call last):
  File "/Users/zeke/Documents/Github/SumanyWeb/sumany/summarize/get_model.py", line 32, in <module>
    optimizer = ORTOptimizer.from_pretrained(model_id, feature=task)
  File "/usr/local/lib/python3.9/site-packages/optimum/onnxruntime/optimization.py", line 60, in from_pretrained
    model_class = FeaturesManager.get_model_class_for_feature(feature)
  File "/usr/local/lib/python3.9/site-packages/transformers/onnx/features.py", line 468, in get_model_class_for_feature
    raise KeyError(
KeyError: "Unknown task: summarization. Possible values are [<class 'transformers.models.auto.modeling_auto.AutoModel'>, <class 'transformers.models.auto.modeling_auto.AutoModelForMaskedLM'>, <class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSequenceClassification'>, <class 'transformers.models.auto.modeling_auto.AutoModelForTokenClassification'>, <class 'transformers.models.auto.modeling_auto.AutoModelForMultipleChoice'>, <class 'transformers.models.auto.modeling_auto.AutoModelForQuestionAnswering'>, <class 'transformers.models.auto.modeling_auto.AutoModelForImageClassification'>, <class 'transformers.models.auto.modeling_auto.AutoModelForMaskedImageModeling'>]"`

### Expected behavior

the expected behavior is for it to run and apply optimization/quantization on the summarization model with no errors.

**Comment by zeke-john** [comment]
In this article i found by philschmid: [Accelerated Inference with Optimum and Transformers Pipelines](https://huggingface.co/blog/optimum-inference#4-current-limitations), it says some of the current limitations is that it cant do Seq2Seq tasks like summarization, which is kind of a bummer, but now i know why im getting this error.

**Comment by zeke-john** [comment]
All i had to do was change `task = "summarization"`  to `task = "seq2seq-lm"` while applying optimization/quantization, and now its working fine.
