### ISSUE TITLE
Inference performance drop 22X on GPU hardware with optimum[onnxruntime-gpu] (compared with transformer)

### ISSUE THREAD

**Issue by bugzyz** [huggingface/optimum#365]
### System Info

```shell
pip list:
onnx               1.12.0
onnxruntime-gpu    1.12.1
optimum            1.3.0
...
transformers       4.21.2

docker image: 
nvcr.io/nvidia/tensorrt:22.07-py3

gpu type:
Tesla V100-SXM2-16GB
```

### Who can help?

@JingyaHuang @echarlaix 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction
0. create docker container
```docker run --gpus all -it --name=tensorrtx -d --rm -v /home/ytseng/models:/models nvcr.io/nvidia/tensorrt:22.07-py3```
1. install required python package
```ln -s /usr/local/bin/pip /usr/bin/pip && pip install optimum[onnxruntime-gpu] transformers```
2. save huggingface model and export to onnx
cmd: ```python save_and_export_model.py```
```model_checkpoint = "facebook/m2m100_418M"
transformer_model = "/models/optimum_m2m100/m2m100_transformer"
onnx_model = "/models/optimum_m2m100/m2m100_onnx"


def download_transformer_model():
    from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

    # Load tokenizer and PyTorch weights form the Hub
    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
    pt_model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

    # Save to disk
    tokenizer.save_pretrained(transformer_model)
    pt_model.save_pretrained(transformer_model)


def export_to_onnx_model():
    """
    -------- export to onnx
    """
    from optimum.onnxruntime import ORTModelForSeq2SeqLM

    # Load a model from transformers and export it through the ONNX format
    model = ORTModelForSeq2SeqLM.from_pretrained(model_checkpoint, from_transformers=True)

    # Save the onnx model
    model.save_pretrained(onnx_model)


if __name__ == '__main__':
    download_transformer_model()
    export_to_onnx_model()
```
3. run translation on transformer api and optimum api
testing cmd: ```python run_translation.py trans ; echo '---------------' ; python run_translation.py opt```
```
# -*- coding: utf-8 -*-

import time, logging

import torch, os
import sys
from transformers import AutoTokenizer


logging.basicConfig(level=logging.INFO)


model_checkpoint = "facebook/m2m100_418M"
transformer_model = "/models/optimum_m2m100/m2m100_transformer"
onnx_model = "/models/optimum_m2m100/m2m100_onnx"

loop = 5

if len(sys.argv) != 2:
    logging.error("call with python run_translation.py <backend>")
    exit(1)

chinese_text = "机器学习是人工智能的一个分支。人工智能的研究历史有着一条从以“推理”为重点，到以“知识”为重点，再到以“学习”为重点的自然、清晰的脉络。显然，机器学习是实现人工智能的一个途径，即以机器学习为手段解决人工智能中的问题。机器学习在近30多年已发展为一门多领域交叉学科，涉及概率论、统计学、逼近论、凸分析（英语：Convex analysis）、计算复杂性理论等多门学科。机器学习理论主要是设计和分析一些让计算机可以自动“学习”的算法。机器学习算法是一类从数据中自动分析获得规律，并利用规律对未知数据进行预测的算法。因为学习算法中涉及了大量的统计学理论，机器学习与推断统计学联系尤为密切，也被称为统计学习理论。算法设计方面，机器学习理论关注可以实现的，行之有效的学习算法。很多推论问题属于无程序可循难度，所以部分的机器学习研究是开发容易处理的近似算法。机器学习已广泛应用于数据挖掘、计算机视觉、自然语言处理、生物特征识别、搜索引擎、医学诊断、检测信用卡欺诈、证券市场分析、DNA序列测序、语音和手写识别、战略游戏和机器人等领域"
logging.info(f"chinese_text is {chinese_text}")
logging.info(f"chinese_text length is {len(chinese_text)}")

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
logging.info(f"This test will use device: {device}")


def get_transformer_model():
    from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

    model = M2M100ForConditionalGeneration.from_pretrained(transformer_model).to(device)
    tokenizer = M2M100Tokenizer.from_pretrained(transformer_model)
    return (model, tokenizer)


def get_optimum_onnx_model():
    from optimum.onnxruntime import ORTModelForSeq2SeqLM

    model = ORTModelForSeq2SeqLM.from_pretrained(onnx_model).to(device)
    tokenizer = AutoTokenizer.from_pretrained(transformer_model)
    return (model, tokenizer)


def translate():
    if str(sys.argv[1]) == "trans":
        (model, tokenizer) = get_transformer_model()
    elif str(sys.argv[1]) == "opt":
        (model, tokenizer) = get_optimum_onnx_model()
    else:
        logging.info("backend type is illegal, should be 'opt' or 'trans'")
        exit(1)

    start = time.time()
    for i in range(loop):
        encoded_zh = tokenizer(chinese_text, return_tensors="pt").to(device)
        generated_tokens = model.generate(**encoded_zh, forced_bos_token_id=tokenizer.get_lang_id("en"))
        result = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
        logging.info(f"#{i}: {result}")
    end = time.time()
    total_time = end - start

    logging.info(f"total: {total_time}")
    logging.info(f"loop: {loop}")
    logging.info(f"avg(s): {total_time / loop}")
    logging.info(f"throughput(translation/s): {loop / total_time}")


if __name__ == '__main__':
    translate()

```

### Expected behavior

We expected that the performance results are closed between the transformer backend and optimum[onnxruntime-gpu] backend. But it turns out that optimum is **22X** slower than transformer one. We're not sure if it's related to a latest reported bug #362 , since we noticed that they used seq2seq transformer model with GPU hardware as well.

Here's some output log for no.3 step in previous Reproduction sections.
```
root@ec44f06bb0bf:/workspace# python run_translation.py trans ; echo '---------------' ; python run_translation.py opt
INFO:root:chinese_text is ...
INFO:root:chinese_text length is 460
INFO:root:This test will use device: cuda
INFO:root:Transformer backend is enabled in this test
/usr/local/lib/python3.8/dist-packages/transformers/generation_utils.py:1202: UserWarning: Neither `max_length` nor `max_new_tokens` have been set, `max_length` will default to 200 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
INFO:root:#0: ...
INFO:root:total: 13.273212909698486
INFO:root:loop: 5
INFO:root:avg(s): 2.6546425819396973
INFO:root:throughput(translation/s): 0.3766985457113096
---------------
INFO:root:chinese_text is ...
INFO:root:chinese_text length is 460
INFO:root:This test will use device: cuda
INFO:root:Optimum backend is enabled in this test
/usr/local/lib/python3.8/dist-packages/transformers/generation_utils.py:1202: UserWarning: Neither `max_length` nor `max_new_tokens` have been set, `max_length` will default to 200 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
INFO:root:#0: ...
INFO:root:total: 303.64781045913696
INFO:root:loop: 5
INFO:root:avg(s): 60.72956209182739
INFO:root:throughput(translation/s): 0.016466445097824505
```

**Comment by bugzyz** [comment]
Also, we did some nsight GPU profiling on these execution and got some strange finding. We hope these will help.

no.1: optimum took lots of time on data copy
optimum GPU memops summary
![image](https://user-images.githubusercontent.com/31982774/187638240-6d7f8658-9cc7-4990-a21c-a20def9cda1e.png)
transformer GPU memops summary
![image](https://user-images.githubusercontent.com/31982774/187638499-7c8c2931-a3b2-43f4-92a1-90d635df24b1.png)

no.2: the kernel didn't take too much time for both (compared with time cost by the data copy between host and device)
optimum top GPU kernels cost - CUDA summary (API/Kernels/Memops)
![image](https://user-images.githubusercontent.com/31982774/187639109-585c831c-44be-4e42-8099-b2302ff6c7ad.png)
transformer top GPU kernels cost - CUDA summary (API/Kernels/Memops)
![image](https://user-images.githubusercontent.com/31982774/187638770-59ad10aa-31f0-4f6e-b95d-f72ea56a9521.png)

**Comment by JeroendenBoef** [comment]
I experienced similar performance drops with ORT M2M100 vs Pytorch version. Quantizing the model does help, making the ORT model about 1.2x slower on CPU and 4x slower on GPU in comparison to the Pytorch model. Optimization might fix this issue but there is no M2M100 onnx model available yet in [the onnxruntime transformers optimization tool](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers). Optimization with a supported but wrong config (bart) doesn't improve the performance.

**Comment by apurvnagvenkar** [comment]
I am facing similar issue interms of inference speed. Able to maintain the accuracy but inference speed shoots up. I am trying this on T5 model.

**Comment by JingyaHuang** [comment]
Hi @bugzyz,

Thanks for reporting and the detailed profiling results. 

Indeed there were significant overheads on data copying between host and device while using CUDA execution provider. ONNX Runtime by default copies inputs from the host and copies outputs back to the host which leads to a longer execution time. 

To avoid this, we need to allocate memory for inputs and outputs on the device prior to the execution with IO binding. The [support on Optimum](https://github.com/huggingface/optimum/pull/421) has just been merged, now we will use IO binding by default when using CUDA EP.

Do you want to have a try and tell us if it helps? 

P.S. There will be no code change, ORTModels will use IOBinding by default when using CUDA execution provider. You can install optimum from the main branch with the following command:
```
python -m pip install git+https://github.com/huggingface/optimum.git#egg=optimum[onnxruntime-gpu]
```

**Comment by bugzyz** [comment]
Hi @JingyaHuang,

Thanks for the new feature! Sure, we want to have a try on this to see onnx/optimum's performance with this enhancement. 

Btw, do you have any performance test report by your side? It will be great if you can share it to us so that we can have a expectation on the acceleration. :)

**Comment by bugzyz** [comment]
@JingyaHuang 

Thanks for the new feature. I validate the latest optimum with previous code. The optimum ran faster than original transformer one. (latency: 2.73s vs 2.13s)

🆘🆘🆘But there's a warning shows up and confuses me as shown below. **Am I allocating the model to the correct device(GPU)**?🆘🆘🆘

Confused warning:
```/usr/local/lib/python3.8/dist-packages/transformers/generation_utils.py:1442: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cuda, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.```

python run_translation.py opt
```
# -*- coding: utf-8 -*-

import time, logging

import torch, os
import sys
from transformers import AutoTokenizer


logging.basicConfig(level=logging.INFO)


model_checkpoint = "facebook/m2m100_418M"
transformer_model = "/models/optimum_m2m100/m2m100_transformer"
onnx_model = "/models/optimum_m2m100/m2m100_onnx"
onnx_opt_lvl_1_model = "/models/optimum_m2m100/m2m100_onnx_opt_lvl1"
onnx_opt_lvl_2_model = "/models/optimum_m2m100/m2m100_onnx_opt_lvl2"
onnx_opt_lvl_99_model = "/models/optimum_m2m100/m2m100_onnx_opt_lvl99"
onnx_opt_lvl_1_gpu_model = "/models/optimum_m2m100/m2m100_onnx_opt_lvl1_gpu"
onnx_opt_lvl_2_gpu_model = "/models/optimum_m2m100/m2m100_onnx_opt_lvl2_gpu"
onnx_opt_lvl_99_gpu_model = "/models/optimum_m2m100/m2m100_onnx_opt_lvl99_gpu"

loop = 10

if len(sys.argv) != 2:
    logging.error("call with python run_translation.py <backend>")
    exit(1)

chinese_text = "机器学习是人工智能的一个分支。人工智能的研究历史有着一条从以“推理”为重点，到以“知识”为重点，再到以“学习”为重点的自然、清晰的脉络。显然，机器学习是实现人工智能的一个途径，即以机器学习为手段解决人工智能中的问题。机器学习在近30多年已发展为一门多领域交叉学科，涉及概率论、统计学、逼近论、凸分析（英语：Convex analysis）、计算复杂性理论等多门学科。机器学习理论主要是设计和分析一些让计算机可以自动“学习”的算法。机器学习算法是一类从数据中自动分析获得规律，并利用规律对未知数据进行预测的算法。因为学习算法中涉及了大量的统计学理论，机器学习与推断统计学联系尤为密切，也被称为统计学习理论。算法设计方面，机器学习理论关注可以实现的，行之有效的学习算法。很多推论问题属于无程序可循难度，所以部分的机器学习研究是开发容易处理的近似算法。机器学习已广泛应用于数据挖掘、计算机视觉、自然语言处理、生物特征识别、搜索引擎、医学诊断、检测信用卡欺诈、证券市场分析、DNA序列测序、语音和手写识别、战略游戏和机器人等领域"
logging.info(f"chinese_text is {chinese_text}")
logging.info(f"chinese_text length is {len(chinese_text)}")

device = torch.device('cuda:0')
logging.info(f"This test will use device: {device}")


def get_transformer_model():
    from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

    model = M2M100ForConditionalGeneration.from_pretrained(transformer_model).to(device)
    tokenizer = M2M100Tokenizer.from_pretrained(transformer_model)
    return (model, tokenizer)


def get_optimum_onnx_model():
    from optimum.onnxruntime import ORTModelForSeq2SeqLM

    model = ORTModelForSeq2SeqLM.from_pretrained(onnx_model).to(device)
    tokenizer = AutoTokenizer.from_pretrained(transformer_model)
    return (model, tokenizer)


def get_optimum_opt_onnx_model(lvl: int, has_gpu: bool):
    # Load the optimization configuration detailing the optimization we wish to apply
    if not has_gpu:
        if lvl == 1:
            opt_save_dir = onnx_opt_lvl_1_model
        elif lvl == 2:
            opt_save_dir = onnx_opt_lvl_2_model
        elif lvl == 99:
            opt_save_dir = onnx_opt_lvl_99_model
        else:
            raise ValueError("opt parameter unsupported")
    else:
        if lvl == 1:
            opt_save_dir = onnx_opt_lvl_1_gpu_model
        elif lvl == 2:
            opt_save_dir = onnx_opt_lvl_2_gpu_model
        elif lvl == 99:
            opt_save_dir = onnx_opt_lvl_99_gpu_model
        else:
            raise ValueError("opt parameter unsupported")

    from optimum.onnxruntime import ORTOptimizer, ORTModelForSeq2SeqLM
    from optimum.onnxruntime.configuration import OptimizationConfig

    model = ORTModelForSeq2SeqLM.from_pretrained(onnx_model).to(device)
    tokenizer = AutoTokenizer.from_pretrained(transformer_model)
    optimizer = ORTOptimizer.from_pretrained(model)
    # Apply optimization and save the resulting model
    optimization_config = OptimizationConfig(optimization_level=lvl, optimize_for_gpu=has_gpu)
    optimizer.optimize(save_dir=opt_save_dir, optimization_config=optimization_config, file_suffix=None)
    model = ORTModelForSeq2SeqLM.from_pretrained(opt_save_dir, file_name="model.onnx").to(device)

    return (model, tokenizer)


def translate():
    if str(sys.argv[1]) == "trans":
        logging.info(f"Transformer backend is enabled in this test")
        (model, tokenizer) = get_transformer_model()
    elif str(sys.argv[1]) == "opt":
        logging.info(f"Optimum backend is enabled in this test")
        (model, tokenizer) = get_optimum_onnx_model()
    elif str(sys.argv[1]) == "opt_1_gpu":
        logging.info(f"Optimum backend is enabled in this test, optimization is enable for level 1 and has_gpu=True")
        (model, tokenizer) = get_optimum_opt_onnx_model(1, True)
    elif str(sys.argv[1]) == "opt_2_gpu":
        logging.info(f"Optimum backend is enabled in this test, optimization is enable for level 2 and has_gpu=True")
        (model, tokenizer) = get_optimum_opt_onnx_model(2, True)
    elif str(sys.argv[1]) == "opt_99_gpu":
        logging.info(f"Optimum backend is enabled in this test, optimization is enable for level 99 and has_gpu=True")
        (model, tokenizer) = get_optimum_opt_onnx_model(99, True)
    elif str(sys.argv[1]) == "opt_1_no_gpu":
        logging.info(f"Optimum backend is enabled in this test, optimization is enable for level 1 and has_gpu=False")
        (model, tokenizer) = get_optimum_opt_onnx_model(1, False)
    elif str(sys.argv[1]) == "opt_2_no_gpu":
        logging.info(f"Optimum backend is enabled in this test, optimization is enable for level 2 and has_gpu=False")
        (model, tokenizer) = get_optimum_opt_onnx_model(2, False)
    elif str(sys.argv[1]) == "opt_99_no_gpu":
        logging.info(f"Optimum backend is enabled in this test, optimization is enable for level 99 and has_gpu=False")
        (model, tokenizer) = get_optimum_opt_onnx_model(99, False)
    else:
        logging.info("backend type is illegal, should be 'opt' or 'trans'")
        exit(1)

    start = time.time()
    for i in range(loop):
        encoded_zh = tokenizer(chinese_text, return_tensors="pt").to(device)
        generated_tokens = model.generate(**encoded_zh, forced_bos_token_id=tokenizer.get_lang_id("en"))
        result = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
        logging.debug(f"#{i}: {result}")
    end = time.time()
    total_time = end - start

    logging.info(f"total: {total_time}")
    logging.info(f"loop: {loop}")
    logging.info(f"avg(s): {total_time / loop}")
    logging.info(f"throughput(translation/s): {loop / total_time}")


if __name__ == '__main__':
    translate()

```

**Comment by bugzyz** [comment]
Thanks @JingyaHuang for the confirmation. 

One more minor found from us is that we used to create device by `device = torch.device('cuda')`. But it leads to this error after using the latest optimum. Convert it into `device = torch.device('cuda:0')` will solve the error.

```
# error msg

Traceback (most recent call last):
File "run_translation.py", line 73, in <module>
translate()
File "run_translation.py", line 60, in translate
generated_tokens = model.generate(**encoded_zh, forced_bos_token_id=tokenizer.get_lang_id("en"))
File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/transformers/generation_utils.py", line 1339, in generate
model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
File "/usr/local/lib/python3.8/dist-packages/transformers/generation_utils.py", line 583, in _prepare_encoder_decoder_kwargs_for_generation
model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
File "/usr/local/lib/python3.8/dist-packages/optimum/onnxruntime/modeling_seq2seq.py", line 648, in __call__
return self.forward(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/optimum/onnxruntime/modeling_seq2seq.py", line 623, in forward
io_binding, output_shapes, output_buffers = self.prepare_io_binding(input_ids, attention_mask)
File "/usr/local/lib/python3.8/dist-packages/optimum/onnxruntime/modeling_seq2seq.py", line 577, in prepare_io_binding
io_binding.bind_input(
File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 458, in bind_input
C.OrtDevice(
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
1. onnxruntime.capi.onnxruntime_pybind11_state.OrtDevice(arg0: int, arg1: int, arg2: int)

Invoked with: 1, 0, None
```

**Comment by bugzyz** [comment]
The feature is very valuable for user like us to use optimum. Big thanks! 🎉 @JingyaHuang

**Comment by fxmarty** [comment]
Thanks, can reproduce and will fix the bug shortly. Our nightly workflows for GPU appear to have been broken, will try to fix as well.

**Comment by fxmarty** [comment]
Let's close for now, let us know if there are any other issues!
