### ISSUE TITLE
Errors on initializing of ORTOptimizer for ORTModelForSeq2SeqLM (from disk and in memory)

### ISSUE THREAD

**Issue by JeroendenBoef** [huggingface/optimum#366]
### System Info

```shell
OS: Ubuntu 20.04.4 LTS
GPU: NVIDIA GTX 3080TI

python: 3.9.7
onnx == 1.11.0
onnruntime == 1.10.0
torch == 1.11.0+cu113
transformers == 4.21.2
optimum == nightly build
```

### Who can help?

@echarlaix @JingyaHuang 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Optimization of seq2seq models as described in the example [here](https://moon-ci-docs.huggingface.co/docs/optimum/pr_294/en/onnxruntime/optimization#optimization-examples) triggers errors.

Trying to optimize a seq2seqmodel that has been loaded into memory with `ORTModel()` triggers a `TypeError` as the `InferenceSession` object cannot be pickled (this holds for seq2seq such as m2m100, sshleifer/distilbart-cnn-12-6 from the example but also for other architectures such as sequenceclassification head Roberta).

Loading the model from a local file or the Huggingface hub works for non-seq2seq models but triggers an OSError for seq2seq as it looks for a single `model.onnx`. Feeding a separate encoder/decoder to the optimizer results in an `UnicodeDecodeError`. This was tested on both quantized and unquantized ORT models.

I have exported the seq2seq model as:
```
from optimum.onnxruntime.configuration import OptimizationConfig
from optimum.onnxruntime import ORTOptimizer, ORTModelForSeq2SeqLM
model = ORTModelForSeq2SeqLM.from_pretrained("facebook/m2m100_418M", from_transformers=True
```

In memory model optimizer:
```
optimizer = ORTOptimizer.from_pretrained(model, feature="seq2seq-lm")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/optimum/onnxruntime/optimization.py", line 61, in from_pretrained
    model = model_class.from_pretrained(model_name_or_path)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 423, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 725, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    original_kwargs = copy.deepcopy(kwargs)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/jdenboef/miniconda3/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession' object

```

Initializing optimizer on the folder with the `.onnx` encoder, decoder and decoder_with_past:
```
optimizer = ORTOptimizer.from_pretrained("quantized_m2m100/", feature="seq2seq-lm")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/optimum/onnxruntime/optimization.py", line 61, in from_pretrained
    model = model_class.from_pretrained(model_name_or_path)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1906, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory quantized_m2m100/.
```

Initializing optimizer directly on just the encoder:
```
optimizer = ORTOptimizer.from_pretrained("quantized_m2m100/encoder_model.onnx", feature="seq2seq-lm")

Traceback (most recent call last):
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 704, in get_file_from_repo
    resolved_file = cached_path(
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 284, in cached_path
    output_path = get_from_cache(
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 502, in get_from_cache
    _raise_for_status(r)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 417, in _raise_for_status
    raise RepositoryNotFoundError(
transformers.utils.hub.RepositoryNotFoundError: 401 Client Error: Repository not found for url: https://huggingface.co/quantized_m2m100/encoder_model.onnx/resolve/main/preprocessor_config.json. If the repo is private, make sure you are authenticated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/onnx/utils.py", line 88, in get_preprocessor
    return AutoProcessor.from_pretrained(model_name)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/models/auto/processing_auto.py", line 187, in from_pretrained
    preprocessor_config_file = get_file_from_repo(
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 715, in get_file_from_repo
    raise EnvironmentError(
OSError: quantized_m2m100/encoder_model.onnx is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/optimum/onnxruntime/optimization.py", line 59, in from_pretrained
    preprocessor = get_preprocessor(model_name_or_path)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/onnx/utils.py", line 96, in get_preprocessor
    feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/models/auto/feature_extraction_auto.py", line 288, in from_pretrained
    config_dict, _ = FeatureExtractionMixin.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/jdenboef/miniconda3/lib/python3.9/site-packages/transformers/feature_extraction_utils.py", line 456, in get_feature_extractor_dict
    text = reader.read()
  File "/home/jdenboef/miniconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 27: invalid continuation byte
```

On a minor sidenote, the example of optimization is currently missing the required `feature` argument for `ORTOptimizer.from_pretrained()`.

### Expected behavior

It is expected that an `ORTOptimizer()` can be initialized on either the in memory model or from the model folder for seq2seq models.

**Comment by JeroendenBoef** [comment]
Closed as the issue is fixed with a clean rebuild of optimum nightly build
