### ISSUE TITLE
Optimizing DeBERTaV2 with fp16 not working

### ISSUE THREAD

**Issue by caffeinetoomuch** [huggingface/optimum#608]
### System Info

```shell
A6000 (Driver Version: 515.86.01, CUDA Version: 11.7)
Python 3.9

onnx                      1.12.0
onnxruntime-gpu           1.13.1
optimum                   1.5.1
torch                     1.13.0
transformers              4.22.2
```

### Who can help?

@lewtun, @michaelbenayoun

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
model_name_or_path = "my_check_point"
optimization_config = AutoOptimizationConfig.O4(for_gpu=True)
model = ORTModelForSequenceClassification.from_pretrained(
    model_name_or_path, from_transformers=True, provider="CUDAExecutionProvider"
)

optimizer = ORTOptimizer.from_pretrained(model)
optimizer.optimize(
    optimization_config=optimization_config, save_dir=save_dir, use_external_data_format=True
)
```

This optimization code snippet produces `Exception: Incomplete symbolic shape inference` and here is the stacktrace:
```
12-19 01:34:09 [onnx_model_bert] INFO     - opset version: 12
Traceback (most recent call last):
  File "/scripts/optimize_sentence_fluency.py", line 126, in <module>
    main()
  File "/scripts/optimize_sentence_fluency.py", line 116, in main
    optimizer.optimize(
  File "/home/.local/lib/python3.9/site-packages/optimum/onnxruntime/optimization.py", line 151, in optimize
    optimizer.convert_float_to_float16(keep_io_types=True)
  File "/home/.local/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 594, in convert_float_to_float16
    model = shape_infer_helper.infer_shapes(model, auto_merge=True, guess_output_rank=False)
  File "/home/.local/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../../tools/symbolic_shape_infer.py", line 2347, in infer_shapes
    raise Exception("Incomplete symbolic shape inference")
Exception: Incomplete symbolic shape inference
```

### Expected behavior

We get an optimized onnx graph.

**Comment by michaelbenayoun** [comment]
Hi @ice-americano ,

After looking into it, it seems that it fails when trying to perform shape inference on the `FusedMatMul` operator, which is created when `optimization_level >= 2`. I submitted a [PR](https://github.com/microsoft/onnxruntime/pull/14019) that should fix that to ONNX Runtime. 

In the mean time, a solution for you would be to simply set `optimization_level=1`:

```python
from optimum.onnxruntime import OptimizationConfig

optimization_config = OptimizationConfig(
    optimization_level=1,
    enable_transformers_specific_optimizations=True,
    enable_gelu_approximation=True,
    fp16=True,
)
```

**Comment by ice-americano** [comment]
@regisss I tried optimization with `disable_shape_inference=True`, but default shape inference seems to fail due to protobuf size. I am currently passing `use_external_data_format=True` and `one_external_file=True` for `ORTOptimizer.optimize`, and everything seems to work if I set `fp16=False` for `OptimizationConfig`. In my case, I need fp16 conversion for better inference speed :cry: Any clue on the following stacktrace?

```
01-02 12:17:31 [onnx_model  ] INFO     - Skip removing useless cast nodes since shape inference failed.
01-02 12:17:33 [fusion_skiplayernorm] WARNING  - symbolic shape inference disabled or failed.
01-02 12:17:42 [fusion_base ] INFO     - Fused FastGelu(GeluApproximation) count: 26
01-02 12:17:42 [onnx_model_bert] INFO     - opset version: 12
Traceback (most recent call last):
  File "/workspace/scripts/optimize.py", line 128, in <module>
    main()
  File "/workspace/scripts/optimize.py", line 117, in main
    optimizer.optimize(
  File "/home/user/.local/lib/python3.9/site-packages/optimum/onnxruntime/optimization.py", line 160, in optimize
    optimizer.convert_float_to_float16(
  File "/home/user/.local/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 612, in convert_float_to_float16
    fp16_model = convert_float_to_float16(model, **parameters)
  File "/home/user/.local/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../float16.py", line 203, in convert_float_to_float16
    model = func_infer_shape(model)
  File "/home/user/.local/lib/python3.9/site-packages/onnx/shape_inference.py", line 39, in infer_shapes
    model_str = model if isinstance(model, bytes) else model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3696658199
```

**Comment by regisss** [comment]
@ice-americano In that case I think you will have to wait for @michaelbenayoun's PR to be merged.
Or maybe you can try to load your model directly in fp16 (if it has fp16 weights) or try to quantize it as suggested [here](https://github.com/huggingface/optimum/issues/222#issuecomment-1211705229) by @JingyaHuang.

**Comment by puyuanOT** [comment]
I got the same issue. Is there a solution for this?

**Comment by regisss** [comment]
@puyuanOT We need to wait for the next release of ONNXRuntime which will have a fix for fp16 conversion issues: https://github.com/microsoft/onnxruntime/pull/15067

**Comment by puyuanOT** [comment]
Thanks for the information!

**Comment by fxmarty** [comment]
Closing in favor of https://github.com/huggingface/optimum/issues/901
