### ISSUE TITLE
Inference with ORT failed with Bloom-560m model

### ISSUE THREAD

**Issue by ytaous** [huggingface/optimum#692]
### System Info

```shell
Optimum - latest from github
Python - 3.8
platform NVidia V100
```

### Who can help?

@JingyaHuang 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. clone from Optimum under, say /scratch/workspaceblobstore/users/ettao/opt-bloom dir
2. cd optimum && python setup install
3. run this cmd:

python -m torch.distributed.launch --nproc_per_node=8 /ws/optimum/examples/onnxruntime/training/language-modeling/run_clm.py --model_name_or_path bigscience/bloom-560m --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --label_smoothing 0.1 --do_eval --output_dir /dev/shm --overwrite_output_dir --max_steps 200 --logging_steps 20 --per_device_eval_batch_size 2 --fp16 --inference_with_ort

Getting error:

[ERROR!] Evaluation with ONNX Runtime is not available for bigscience/bloom-560m model. Set `inference_with_ort=False` to evaluate with PyTorch.
Traceback (most recent call last):
  File "/scratch/workspaceblobstore/users/ettao/opt-bloom/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 593, in <module>
    main()
  File "/scratch/workspaceblobstore/users/ettao/opt-bloom/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 559, in main
    metrics = trainer.evaluate(inference_with_ort=inference_args.inference_with_ort)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/optimum-1.6.2.dev0-py3.8.egg/optimum/onnxruntime/trainer.py", line 803, in evaluate
    output = eval_loop(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/optimum-1.6.2.dev0-py3.8.egg/optimum/onnxruntime/trainer.py", line 974, in evaluation_loop_ort
    ort_model = ort_model_cls.from_pretrained(model_id=model_id, file_name=file_name)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/optimum-1.6.2.dev0-py3.8.egg/optimum/onnxruntime/modeling_ort.py", line 557, in from_pretrained
    return super().from_pretrained(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/optimum-1.6.2.dev0-py3.8.egg/optimum/modeling_base.py", line 325, in from_pretrained
    return from_pretrained_method(
TypeError: _from_pretrained() got an unexpected keyword argument 'file_name'
[Errno 2] No such file or directory: '/dev/shm/transformer.word_embeddings.weight'

### Expected behavior

ORT team would like to do inferencing benchmark for Bloom-560m between

torch baseline vs. ORT inferencing

and possibly identify areas to improve on ORT. It will be convenient if the cmd above would work for bloom-560m model (and a few more larger bloom models).
I hope the cmd is correct, and if there's any workaround for now, it will be great.
Thanks.

**Comment by JingyaHuang** [comment]
@ytaous Thanks for reporting, I will fix the example asap.

**Comment by ytaous** [comment]
> @ytaous Thanks for reporting, It seems that `ORTTrainer` failed to load the model. I will fix the example asap.

do_train works fine, though - FYI

**Comment by cyang49** [comment]
I tried with the same command and getting a different error. What's this `config.json` and how can I produce it correctly?
```
[ERROR!] Evaluation with ONNX Runtime is not available for bigscience/bloom-560m model. Set `inference_with_ort=False` to evaluate with PyTorch.
Traceback (most recent call last):
  File "/net/storage149/mnt/md0/ccyang/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 593, in <module>
    main()
  File "/net/storage149/mnt/md0/ccyang/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 559, in main
    metrics = trainer.evaluate(inference_with_ort=inference_args.inference_with_ort)
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/onnxruntime/trainer.py", line 803, in evaluate
    output = eval_loop(
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/onnxruntime/trainer.py", line 974, in evaluation_loop_ort
    ort_model = ort_model_cls.from_pretrained(model_id=model_id, file_name=file_name)
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 581, in from_pretrained
    return super().from_pretrained(
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/modeling_base.py", line 313, in from_pretrained
    raise OSError(f"config.json not found in {model_id} local folder")
OSError: config.json not found in /dev/shm local folder
```

**Comment by JingyaHuang** [comment]
Hi @ytaous, to follow up. While trying to reproduce the issue, I got an error message for missing config other than missing weight by using the current main branch of Optimum(just like @cyang49 mentioned). 

Actually inference with ONNX Runtime in `ORTTrainer` is bugged right now due to recent migration of ONNX exporter and the fact that we now adopt the subclasses of `ORTModel` in optimum.

In the PR #709, I put a temporary workaround to enable the use of ort for inference. However, due to current constraint in `ORTModelForCausalLM`, it will only use a decoder without cached past keys and values(as current `ORTModelForCausalML` doesn't support loss as output which is needed for evaluation in `ORTTrainer`), so there will be extra overhead on recomputing them.

We are working on refactoring `ORTModel` to support custom output(namely `loss`). Before that, for benchmarking decoding task, I suggest you to use directly `ORTModelForCausalLM`.

**Comment by JingyaHuang** [comment]
Here is an example of using `ORTModelForCausalLM` to compare to PyTorch baseline: https://github.com/JingyaHuang/onnxruntime-inference-benchmark/blob/main/benchmarks/onnxruntime/test_profiling_gpt2.py

Hope it could help.

**Comment by ytaous** [comment]
Thanks a lot !!

**Comment by cyang49** [comment]
@JingyaHuang I tried modifying the `test_profiling_gpt2.py` script to use `bigscience/bloom-560m` and there is some cryptic error messages. Could you suggest how to debug this?
```
use_past = False is different than use_present_in_outputs = True, the value of use_present_in_outputs value will be used for the outputs.
/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py:106: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out
 of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  base = torch.tensor(
/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py:657: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value wil
l be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if src_length > 1:
/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/transformers/models/bloom/modeling_bloom.py:69: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will
 be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_key_values_length > 0:
2023-01-24 15:03:58.500830823 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CP
U to improve perf.
2023-01-24 15:03:58.500876203 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-01-24 15:04:01.316073112 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CP
U to improve perf.
2023-01-24 15:04:01.316104532 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-01-24 15:04:06.368452184 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CP
U to improve perf.
2023-01-24 15:04:06.368485945 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-01-24 15:04:10.096920788 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CP
U to improve perf.
2023-01-24 15:04:10.096955037 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
seq_len:  8
num_beam:  5
  0%|                                                                                                                                                                                                                                                            | 0/5 [00:00<?, ?it/s]
2023-01-24 15:04:13.854698837 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running Concat node. Name:'/transformer/h.0/self_attention/Concat_4' Status Message: concat.cc:156 PrepareForCompute Non concat axis dimensions must match: Axis
 0 has mismatched dimensions of 80 and 5
  0%|                                                                                                                                                                                                                                                            | 0/5 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/net/storage149/mnt/md0/ccyang/onnxruntime-inference-benchmark/benchmarks/onnxruntime/test_profiling_bloom-jamie.py", line 123, in <module>
    df_onnx = benchmark(seq_len, onnx_model, tokenizer, device, frame="ONNX", num_beam=num_beam, iterations=5)
  File "/net/storage149/mnt/md0/ccyang/onnxruntime-inference-benchmark/benchmarks/onnxruntime/test_profiling_bloom-jamie.py", line 65, in benchmark
    generated_tokens = model.generate(
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1608, in generate
    return self.beam_search(
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2799, in beam_search
    outputs = self(
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/modeling_base.py", line 85, in __call__
    return self.forward(*args, **kwargs)
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/onnxruntime/modeling_decoder.py", line 749, in forward
    outputs = self.decoder_with_past(
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/onnxruntime/modeling_decoder.py", line 326, in __call__
    return self.forward(*args, **kwargs)
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/optimum/onnxruntime/modeling_decoder.py", line 309, in forward
    outputs = self.session.run(None, onnx_inputs)
  File "/home/ccyang/nfs/ccyang/miniconda3/envs/fm/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'/transformer/h.0/self_attention/Concat_4' Status Message: concat.cc:156 PrepareForCompute Non concat axis dimensions must match: Axis 
0 has mismatched dimensions of 80 and 5
```

**Comment by JingyaHuang** [comment]
@cyang49 It seems that the inputs' dimensions are illegal. Any code you can provide for me to reproduce the error?

**Comment by cyang49** [comment]
> @cyang49 It seems that the inputs' dimensions are illegal. Any code you can provide for me to reproduce the error?

@JingyaHuang thanks. Here's a diff I generated from `test_profiling_gpt2.py` and my script

```
26c26
< def get_transformer_model(model_checkpoint, device):
---
> def get_transformer_model(model_checkpoint):
27a28
>     device = torch.device("cuda:0")
35,36c36,38
< def get_onnx_model(model_checkpoint, device):
<     model = ORTModelForCausalLM.from_pretrained(model_checkpoint, from_transformers=True).to(device)
---
> def get_onnx_model(model_checkpoint):
>     device = torch.device("cuda:0")
>     model = ORTModelForCausalLM.from_pretrained("optimum/gpt2").to(device)
105c107
< model_id = "bigscience/bloom-560m"
---
> model_id = "gpt2"
108c110
< pt_model, tokenizer = get_transformer_model(model_id, device)
---
> pt_model, tokenizer = get_transformer_model(model_id)
110c112
< onnx_model, _ = get_onnx_model(model_id, device)
---
> onnx_model, _ = get_onnx_model(model_id)
114c116
< seq_lengths = [8, 16, 32, 64, 128] #, 256, 512] #
---
> seq_lengths = [8, 16, 32, 64, 128, 256, 512] #
121c123
<         df_onnx = benchmark(seq_len, onnx_model, tokenizer, device, frame="ONNX", num_beam=num_beam, iterations=5)
---
>         df_onnx = benchmark(seq_len, onnx_model, tokenizer, device, frame="ONNX", num_beam=num_beam, iterations=500)
123c125
<         df_pt = benchmark(seq_len, pt_model, tokenizer, device, frame="PyTorch", num_beam=num_beam, iterations=5)
---
>         df_pt = benchmark(seq_len, pt_model, tokenizer, device, frame="PyTorch", num_beam=num_beam, iterations=500)
129c131
<     res.to_pickle(f"res_ort_bloom-560m_beam5_{seq_len}.pkl")
---
>     res.to_pickle(f"t4_res_ort_gpt2_beam5_{seq_len}.pkl")
```

**Comment by JingyaHuang** [comment]
This issue is closed as previously we talk about `ORTTrainer`. But there is sti
