### ISSUE TITLE
Export donut to ONNX

### ISSUE THREAD

**Issue by aymanechilah** [huggingface/optimum#938]
How I can export donut-base-finetuned-rvlcdip to ONNX? I tried the notebook provided by HF but didn't work. It is possible with optimum library? Thanks

**Comment by fxmarty** [comment]
Hi @aymanechilah , you should be able to export it with `optimum-cli export onnx donut-base-finetuned-rvlcdip donut_onnx/` as explained in the documentation: https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model

Feel free to let us know if you encounter any issue!

**Comment by fxmarty** [comment]
Actually exporting this model fails:

```
Traceback (most recent call last):
  File "/home/fxmarty/anaconda3/envs/hf-inf/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/fxmarty/hf_internship/optimum/optimum/commands/optimum_cli.py", line 167, in main
    service.run()
  File "/home/fxmarty/hf_internship/optimum/optimum/commands/export/onnx.py", line 38, in run
    main_export(
  File "/home/fxmarty/hf_internship/optimum/optimum/exporters/onnx/__main__.py", line 447, in main_export
    _, onnx_outputs = export_models(
  File "/home/fxmarty/hf_internship/optimum/optimum/exporters/onnx/convert.py", line 609, in export_models
    export(
  File "/home/fxmarty/hf_internship/optimum/optimum/exporters/onnx/convert.py", line 697, in export
    export_output = export_pytorch(
  File "/home/fxmarty/hf_internship/optimum/optimum/exporters/onnx/convert.py", line 438, in export_pytorch
    onnx_export(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fxmarty/hf_internship/optimum/optimum/exporters/onnx/model_patcher.py", line 124, in patched_forward
    outputs = self.orig_forward(*args, **kwargs)
  File "/home/fxmarty/hf_internship/transformers/src/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 609, in forward
    decoder_outputs = self.decoder(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fxmarty/hf_internship/transformers/src/transformers/models/mbart/modeling_mbart.py", line 1850, in forward
    outputs = self.model.decoder(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fxmarty/hf_internship/transformers/src/transformers/models/mbart/modeling_mbart.py", line 1045, in forward
    positions = self.embed_positions(input, past_key_values_length)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/fxmarty/hf_internship/transformers/src/transformers/models/mbart/modeling_mbart.py", line 135, in forward
    return super().forward(positions + self.offset)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

**Comment by fxmarty** [comment]
Looks to be rather an issue on the model itself: https://huggingface.co/naver-clova-ix/donut-base-finetuned-rvlcdip/discussions/2
